export const stages = [
  {
    id: 1,
    number: '00',
    title: 'Pre-Foundational Phase',
    years: 'Historical',
    breakthrough: 'Intelligence is Domain-Specific',
    abbrev: null,
    color: 'slate',
    accent: '#64748b',
    bg: 'from-slate-900/80 to-slate-800/40',
    border: 'border-slate-500/40',
    badge: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    dot: 'bg-slate-500',
    icon: '🌐',
    keyObservations: ['Isolated Domain Theories', 'No Shared Representation', 'Field Silos', 'Local Optimization'],
    domains: ['Biology', 'Economics', 'AI', 'Cognition', 'Ecosystems', 'Governance'],
    transitionTrigger: 'Researchers notice recurring structures: networks, feedback loops, optimization, information flow, and self-organization across domains.',
    gap: 'No shared representation of learning, adaptation, memory, emergence, or transfer existed across any discipline.',
    leadsTo: 'Information-Centric Intelligence',
    detail: {
      overview: {
        summary: 'Before any unified theory was possible, every domain of intelligence — biology, economics, AI, governance, cognition — developed its own entirely isolated theories. A biologist studying neural circuits had no formal language in common with an economist modeling market dynamics. The systems were not just separate; there was no shared conceptual infrastructure to even ask whether they might be related.',
        why: 'The scientific tradition of reductionism drove deep specialization. Fields advanced fastest by narrowing their focus, building domain-specific methods, and ignoring cross-domain signals. This produced extraordinary results within each silo, but created a fragmented landscape where no one was asking the bigger question.',
        significance: 'This stage is the necessary baseline. Understanding why intelligence was treated as domain-specific — and what cracks began to appear — is essential context for the entire UTI research program. The transition trigger was the observation of recurring structural patterns (networks, feedback loops, adaptation) appearing independently in unrelated fields.',
        insight: 'The scientific community was solving the same problems with different notation. The question was whether a unified representation could surface.',
      },
      concepts: [
        {
          title: 'Domain Isolation and Scientific Silos',
          explanation: 'Each field developed its own vocabulary, methods, and theories independently. Neuroscience used "synaptic plasticity"; economics used "learning curves"; AI used "gradient descent" — three names for structurally similar adaptive optimization processes. No formal bridge existed between them.',
        },
        {
          title: 'Cybernetics — The First Attempt at Unification',
          explanation: 'Norbert Wiener\'s cybernetics (1948) was the first serious attempt to create a unified theory of feedback and control across machines, animals, and social systems. It introduced concepts like feedback loops, homeostasis, and goal-directed behavior as universal principles. It ultimately failed to scale, but planted the seed of cross-domain thinking.',
        },
        {
          title: 'Shannon\'s Information Theory',
          explanation: 'Claude Shannon\'s 1948 paper "A Mathematical Theory of Communication" created the first truly substrate-independent framework — bits as a universal currency for information regardless of physical medium. This was the conceptual precursor to ERP-X: a representation that transcends its domain of origin.',
        },
        {
          title: 'General Systems Theory (Bertalanffy)',
          explanation: 'Ludwig von Bertalanffy proposed that systems across all disciplines share common organizational principles — boundaries, inputs, outputs, feedback, and emergence. This was explicitly cross-disciplinary but remained qualitative and lacked formal mathematical grounding.',
        },
        {
          title: 'Complexity Science and the Santa Fe Institute',
          explanation: 'The Santa Fe Institute (founded 1984) brought physicists, economists, biologists, and computer scientists together to study complex adaptive systems. They observed that emergent phenomena — markets, ecosystems, neural activity — shared statistical signatures like power laws, phase transitions, and self-organization. This was the direct intellectual ancestor of structural intelligence theory.',
        },
      ],
      milestones: [
        { year: '1948', event: 'Shannon publishes "A Mathematical Theory of Communication" — first substrate-independent information framework' },
        { year: '1948', event: 'Norbert Wiener\'s "Cybernetics" — first cross-domain theory of feedback and control' },
        { year: '1968', event: 'Bertalanffy formalizes General Systems Theory' },
        { year: '1984', event: 'Santa Fe Institute founded — first institution dedicated to complexity science across domains' },
        { year: '1987', event: 'Kauffman\'s NK fitness landscapes bridge evolution and computational complexity' },
        { year: '1990s', event: 'Scale-free network discovery — power law structures found in biology, internet, and social systems' },
        { year: '2000s', event: 'Network science matures — Barabási shows universal network growth patterns across all domains' },
      ],
      research: {
        foundationalPapers: [
          { title: 'A Mathematical Theory of Communication', authors: 'Claude Shannon', year: 1948, significance: 'The first substrate-independent representation framework — the intellectual seed of ERP-X' },
          { title: 'Cybernetics', authors: 'Norbert Wiener', year: 1948, significance: 'First cross-domain theory of goal-directed adaptive systems' },
          { title: 'Emergence of Scaling in Random Networks', authors: 'Barabási & Albert', year: 1999, significance: 'Universal structural patterns found independently across all complex systems' },
        ],
        keyInsight: 'The same structural signatures (feedback, emergence, power laws, phase transitions) appeared independently across all domains, suggesting a deeper shared substrate.',
        openQuestion: 'Is this structural similarity surface-level coincidence, or evidence of a deeper unified theory of intelligence waiting to be formalized?',
      },
      buildPath: [
        { step: 1, title: 'Read the Foundations', goal: 'Build conceptual vocabulary', tasks: ['Read Shannon\'s original information theory paper', 'Study Wiener\'s cybernetics core concepts', 'Survey Santa Fe Institute complexity research'] },
        { step: 2, title: 'Map the Structural Similarities', goal: 'Identify recurring patterns across 3+ domains', tasks: ['Document feedback loop structures in biology, economics, and AI', 'Map network growth laws across internet, social, and biological systems', 'Identify shared optimization principles across evolution, gradient descent, and markets'] },
        { step: 3, title: 'Build a Cross-Domain Pattern Database', goal: 'First ERP artifact', tasks: ['Create a structured table of concepts that appear independently across 5+ fields', 'Note formal differences in notation despite structural similarity', 'Identify gaps where no shared vocabulary exists'] },
      ],
    },
  },
  {
    id: 2,
    number: '01',
    title: 'Information-Centric Intelligence',
    years: '2017 – Present',
    breakthrough: 'Intelligence as Information Processing',
    abbrev: null,
    color: 'blue',
    accent: '#3b82f6',
    bg: 'from-blue-950/80 to-blue-900/40',
    border: 'border-blue-500/40',
    badge: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    dot: 'bg-blue-500',
    icon: '💡',
    coreInsight: 'Intelligence is adaptive information transformation — not hardcoded behavior.',
    keyCapabilities: ['Representation', 'Prediction', 'Compression', 'Optimization'],
    keyDeliverables: ['Transformers', 'Retrieval Systems', 'Embeddings', 'Reasoning Agents', 'Memory Architectures'],
    leadingOrgs: ['Google DeepMind', 'OpenAI', 'Anthropic', 'Meta AI'],
    shift: 'Input → Output becomes Memory → Reasoning → Adaptation',
    gap: 'Systems remain stateless — no persistent knowledge formation, no cross-domain transfer, no unified epistemic layer.',
    leadsTo: 'Epistemic Intelligence (EEI)',
    detail: {
      overview: {
        summary: 'The Transformer architecture (2017) created the first practically scalable framework for intelligence as information transformation. The key insight was that intelligence could be reduced to a single mathematical primitive: the attention mechanism — computing weighted relationships between all elements of a representation simultaneously. This unlocked parallel processing of language at scale and spawned every major AI system in use today.',
        why: 'The Transformer replaced sequential RNN processing with parallel attention over all tokens simultaneously. This was not just faster — it allowed models to capture long-range dependencies that RNNs couldn\'t. Combined with scaling laws (more data + more compute = predictable capability gains), it created a clear engineering path to increasingly capable systems.',
        significance: 'Every major AI system — GPT-4, Claude, Gemini, LLaMA — is built on this architecture. For the UTI program, Stage 01 is critical because it establishes the baseline: what current AI can do, what it cannot, and exactly what epistemic and structural capabilities are missing.',
        insight: '"Intelligence is not hardcoded behavior. It is adaptive information transformation." This realization — that a single architecture trained on prediction can generate emergent reasoning — is the foundation Stage 02 EEI builds upon.',
      },
      concepts: [
        {
          title: 'The Attention Mechanism',
          explanation: 'Self-attention computes weighted relationships between every pair of elements in a sequence simultaneously. For each token, the model learns which other tokens are relevant (and how much). This captures long-range dependencies that sequential architectures miss. The formula: Attention(Q,K,V) = softmax(QK^T / √d_k)V. The dimension scaling prevents dot products from exploding in high-dimensional space.',
        },
        {
          title: 'Foundation Models and Emergent Capabilities',
          explanation: 'Training a single large model on diverse internet-scale data produces capabilities not explicitly trained for: multi-step arithmetic, code generation, translation, and reasoning. These emergent capabilities appear suddenly as model scale crosses thresholds — a phenomenon that remains poorly understood theoretically but is empirically robust. It suggests that sufficient representational capacity produces general-purpose intelligence from a simple prediction objective.',
        },
        {
          title: 'Representation Learning and Embedding Spaces',
          explanation: 'Neural networks learn to compress high-dimensional inputs into dense vector representations that capture semantic relationships. Words with similar meanings cluster in embedding space; arithmetic works geometrically (king - man + woman ≈ queen). This is the computational analog of what UTI calls "compression of intelligence" — finding low-dimensional structure in high-dimensional reality.',
        },
        {
          title: 'Scaling Laws',
          explanation: 'Kaplan et al. (2020) discovered that model performance scales as a smooth power law with compute, data, and parameters — predictably and across many orders of magnitude. This transformed AI from craft to engineering: you can predict capability gains from scale before training. For UTI, scaling laws raise the question of whether there are similar laws for cross-domain intelligence transfer.',
        },
        {
          title: 'Retrieval-Augmented Generation (RAG)',
          explanation: 'Rather than memorizing all knowledge in model weights, RAG retrieves relevant documents from an external store at inference time. This separates the "reasoning engine" from the "knowledge store" — a first step toward the EEI architecture where memory, retrieval, and reasoning are distinct, composable systems. RAG is Stage 01\'s approximate answer to persistent memory.',
        },
        {
          title: 'In-Context Learning',
          explanation: 'GPT-3 demonstrated that models can learn new tasks from examples in the prompt — without gradient updates. This is a form of meta-learning: the model has learned to learn from its training distribution. For UTI research, in-context learning hints that intelligence representations encode general learning strategies, not just domain facts — the first empirical evidence for cross-domain transfer of learning ability.',
        },
      ],
      milestones: [
        { year: 'Jun 2017', event: '"Attention Is All You Need" — Vaswani et al. (Google Brain) introduces the Transformer' },
        { year: 'Jun 2018', event: 'GPT-1 (OpenAI) — generative pre-training establishes the foundation model paradigm' },
        { year: 'Oct 2018', event: 'BERT (Google) — bidirectional Transformer dominates NLP benchmarks' },
        { year: 'May 2020', event: 'GPT-3 (175B) — emergent few-shot learning appears; scaling laws published' },
        { year: 'Nov 2022', event: 'ChatGPT launches — 100M users in 2 months; AI becomes mainstream' },
        { year: 'Mar 2023', event: 'GPT-4 — multimodal capabilities; passes bar exam, medical boards' },
        { year: 'Nov 2024', event: 'Model Context Protocol (MCP) — Anthropic standardizes tool integration across AI systems' },
      ],
      research: {
        foundationalPapers: [
          { title: 'Attention Is All You Need', authors: 'Vaswani et al.', year: 2017, significance: 'The architecture underlying every major AI system; 100,000+ citations' },
          { title: 'Scaling Laws for Neural Language Models', authors: 'Kaplan et al.', year: 2020, significance: 'Predicts capability gains from scale — transforms AI from craft to engineering' },
          { title: 'Chain-of-Thought Prompting', authors: 'Wei et al.', year: 2022, significance: 'Shows reasoning emerges from prompting structure — first step toward EEI\'s reasoning layer' },
        ],
        keyInsight: 'A single prediction objective at sufficient scale produces emergent general reasoning — but the system remains stateless and lacks persistent, structured knowledge.',
        openQuestion: 'Can we architect systems that not only predict but persistently form, organize, and revise structured knowledge? That question defines Stage 02.',
      },
      buildPath: [
        { step: 1, title: 'Master Transformer Architecture', goal: 'Understand the foundation', tasks: ['Implement self-attention from scratch in Python', 'Build a small GPT-style model with nanoGPT', 'Understand positional encoding, multi-head attention, feed-forward layers'] },
        { step: 2, title: 'Build a RAG System', goal: 'First memory-augmented AI', tasks: ['Set up a vector database (Pinecone, Weaviate, or Chroma)', 'Build semantic search over a document corpus', 'Connect retrieval to an LLM for grounded generation'] },
        { step: 3, title: 'Deploy a Reasoning Agent', goal: 'First agentic system', tasks: ['Build a ReAct-style agent with tool use', 'Add chain-of-thought prompting', 'Measure multi-step task completion rate as baseline for EEI comparison'] },
      ],
    },
  },
  {
    id: 3,
    number: '02',
    title: 'Epistemic Intelligence',
    years: '2024 – 2027',
    breakthrough: 'Intelligence as Knowledge Formation',
    abbrev: 'EEI',
    color: 'violet',
    accent: '#8b5cf6',
    bg: 'from-violet-950/80 to-violet-900/40',
    border: 'border-violet-500/40',
    badge: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
    dot: 'bg-violet-500',
    icon: '🧠',
    coreQuestion: 'Can systems construct, organize, revise, and justify knowledge — not just predict?',
    architectureLayers: ['Persistent Memory', 'Graph Structures', 'Structured Retrieval', 'Multi-hop Reasoning', 'Uncertainty Tracking', 'Self-Reflection'],
    researchOutputs: ['Graph Reasoning Systems', 'Epistemic Memory Agents', 'Reflective AI', 'Causal Retrieval Architectures'],
    leadingOrgs: ['LangGraph', 'Anthropic', 'LlamaIndex', 'Stanford AI Lab'],
    shift: 'Stateless prediction → Persistent epistemic systems',
    gap: 'EEI systems operate within domains — cross-domain transfer and structural invariants remain undiscovered.',
    leadsTo: 'Structural Intelligence Theory',
    detail: {
      overview: {
        summary: 'EEI marks the first major theoretical transition in the UTI roadmap. Where Stage 01 systems predict the next token, EEI systems form, maintain, revise, and justify knowledge structures. The question shifts from "what is the next word?" to "what do I know, how confident am I, and how does this connect to what I already know?" This is the shift from language model to knowledge system.',
        why: 'Stage 01 systems are epistemically empty — they have no persistent model of the world, no uncertainty awareness, no structured knowledge. They confabulate because they have no way to distinguish facts from plausible-sounding completions. EEI fixes this by adding a persistent epistemic layer: a knowledge graph that the system reads from, writes to, and reasons over across sessions.',
        significance: 'EEI is the first practically buildable stage of the UTI program. The components — vector databases, knowledge graphs, LangGraph orchestration, reflection loops — all exist today. EEI is not a future projection; it is a present engineering challenge. A working EEI prototype is the first publishable milestone of the Eternal Research Program.',
        insight: 'The architectural shift is from stateless prediction to persistent epistemic systems. The system must remember what it knows, distinguish known from uncertain, and build structured relationships between concepts over time.',
      },
      concepts: [
        {
          title: 'Persistent Memory Architecture',
          explanation: 'EEI requires three memory types working together: working memory (current context window), episodic memory (history of past interactions and outcomes stored in a vector DB), and semantic memory (a structured knowledge graph of entities and relationships). Unlike RAG which retrieves on demand, EEI memory is continuously updated — the system writes new knowledge to its graph as it learns.',
        },
        {
          title: 'Knowledge Graphs for Structured Reasoning',
          explanation: 'A knowledge graph represents entities as nodes and relationships as edges. Where embeddings capture semantic similarity, graphs capture explicit relational structure: "Einstein worked at the Institute for Advanced Study" is a triple (Einstein, worksAt, IAS). Multi-hop reasoning over graphs allows queries like "who worked at the same institution as someone who co-authored with Einstein?" — impossible for embedding-only retrieval.',
        },
        {
          title: 'Uncertainty Modeling and Epistemic Confidence',
          explanation: 'An epistemic system must distinguish between: facts (high confidence, multiple sources), inferences (derived, moderate confidence), assumptions (low confidence, marked as such), and contradictions (conflicting sources detected). This requires each knowledge node to carry confidence scores, source provenance, and temporal validity. Systems without uncertainty modeling confabulate at confidence — a critical flaw for reliable AI.',
        },
        {
          title: 'Self-Reflection and Meta-Cognition',
          explanation: 'EEI systems can reason about their own knowledge state: "I know X with high confidence, but I\'m uncertain about Y — I should retrieve more information before concluding." This reflection loop is implemented as an explicit reasoning step where the model evaluates its own output against its epistemic state. LLM-as-judge patterns implement this using a separate evaluation model.',
        },
        {
          title: 'Causal Retrieval vs Semantic Retrieval',
          explanation: 'Standard RAG retrieves semantically similar documents. Causal retrieval finds documents connected by causal relationships — not just similar words but logical dependencies. "Why did X happen?" requires traversing a causal graph, not just semantic similarity. EEI systems must support both retrieval modes, which requires causal structure in the knowledge graph.',
        },
        {
          title: 'Multi-hop Reasoning Over Structured Knowledge',
          explanation: 'Multi-hop reasoning answers questions that require multiple inference steps: "What country borders the country that produces the most lithium?" Step 1: find the top lithium producer. Step 2: find its borders. Without structured knowledge, this requires the model to implicitly chain facts — unreliably. With a knowledge graph, each hop is a graph traversal — reliable, traceable, and auditable.',
        },
      ],
      milestones: [
        { year: '2023', event: 'LangGraph released — stateful agent workflows with persistent memory and checkpointing' },
        { year: '2024', event: 'MCP (Model Context Protocol) standardizes tool and memory integration across AI systems' },
        { year: '2024', event: 'First production-grade epistemic memory agents deployed in enterprise research workflows' },
        { year: '2024', event: 'LlamaIndex introduces agentic RAG with structured knowledge extraction' },
        { year: '2025', event: 'First measurable improvements of graph-augmented memory over standard RAG on multi-hop benchmarks' },
        { year: '2025', event: 'EEI prototype published: "Epistemic Intelligence Agent with Persistent Memory and Graph Reasoning"' },
        { year: '2026', event: 'EEI systems adopted in scientific research assistance — first domain-specific epistemic agents' },
        { year: '2027', event: 'Multi-domain EEI agents demonstrate stable knowledge formation across 3+ knowledge domains' },
      ],
      research: {
        foundationalPapers: [
          { title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP', authors: 'Lewis et al.', year: 2020, significance: 'Foundational RAG paper — the memory retrieval architecture EEI builds upon' },
          { title: 'Reflexion: Language Agents with Verbal Reinforcement Learning', authors: 'Shinn et al.', year: 2023, significance: 'Self-reflection agents outperform non-reflective agents on reasoning benchmarks' },
          { title: 'Knowledge Graphs for AI: Survey and Open Challenges', authors: 'Ji et al.', year: 2022, significance: 'Comprehensive survey of knowledge graph techniques relevant to EEI' },
        ],
        keyInsight: 'EEI is not a single technique — it is an architecture. Memory, retrieval, graph reasoning, and reflection must work together as a system. None alone is sufficient.',
        openQuestion: 'Can EEI systems transfer their epistemic structures across domains? If a system builds a knowledge graph of ecosystem dynamics, can that structure inform an economic model? That is Stage 03.',
      },
      buildPath: [
        { step: 1, title: 'Build Persistent Memory System', goal: 'Session-persistent knowledge', tasks: ['Connect LangGraph with a vector database (Chroma/Weaviate)', 'Implement write-on-learn: agent updates memory after each session', 'Build retrieval that combines semantic search with recency weighting'] },
        { step: 2, title: 'Add Structured Knowledge Graph', goal: 'Relational reasoning capability', tasks: ['Set up Neo4j or a graph DB', 'Implement entity/relationship extraction from documents', 'Build graph-augmented retrieval alongside vector retrieval'] },
        { step: 3, title: 'Add Reflection and Uncertainty', goal: 'Epistemic confidence layer', tasks: ['Add an LLM-as-judge step evaluating outputs for consistency', 'Implement confidence scoring on knowledge graph nodes', 'Add contradiction detection: flag conflicting sources in the graph'] },
        { step: 4, title: 'Measure vs RAG Baseline', goal: 'Publishable result', tasks: ['Run multi-hop QA benchmarks (MuSiQue, HotpotQA)', 'Measure hallucination rate vs standard RAG', 'Document: does graph memory improve multi-hop accuracy?'] },
      ],
    },
  },
  {
    id: 4,
    number: '03',
    title: 'Structural Intelligence Theory',
    years: '2026 – 2031',
    breakthrough: 'All Intelligent Systems Share Structural Properties',
    abbrev: null,
    color: 'amber',
    accent: '#f59e0b',
    bg: 'from-amber-950/80 to-amber-900/40',
    border: 'border-amber-500/40',
    badge: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    dot: 'bg-amber-500',
    icon: '🔗',
    coreQuestion: 'What structures remain invariant across domains?',
    crossDomainLinks: ['Ecosystems ↔ Economies', 'Neural Networks ↔ Social Systems', 'Climate ↔ Optimization Landscapes'],
    researchOutputs: ['Invariant Detectors', 'Universal Graph Schemas', 'Structural Embeddings', 'Topology-Preserving Mappings'],
    requiredMath: ['Graph Theory', 'Dynamical Systems', 'Information Geometry', 'Category Theory'],
    leadingOrgs: ['MIT CSAIL', 'Santa Fe Institute', 'DeepMind Research'],
    gap: 'Structural invariants identified in theory but no formal transfer operator — ERP-X engine not yet built.',
    leadsTo: 'ERP-X Cross-Domain Intelligence',
    detail: {
      overview: {
        summary: 'Stage 03 is the transition from AI engineering to universal abstraction. The core discovery is that different intelligent systems — ecosystems, neural networks, economies, governance structures — share deep structural properties: feedback loops with the same topology, optimization landscapes with the same curvature properties, emergence thresholds at the same informational complexity. The research goal is to find and formalize these invariants.',
        why: 'EEI systems (Stage 02) demonstrate that structured knowledge helps within a domain. Stage 03 asks whether the structure itself generalizes. If ecosystem competition and market competition share a graph structure, then knowledge learned in one domain might transfer to the other — not just the facts, but the relational patterns. This requires formal structural theory, not just intuition.',
        significance: 'Structural Intelligence Theory is the mathematical core of UTI. Without it, ERP-X (Stage 04) has no formal basis for transfer. This stage defines what an "invariant" is, how to detect it, and how to encode it in a domain-agnostic representation. The outputs of this stage — universal graph schemas, structural embeddings, topology-preserving mappings — are the raw materials for the transfer engine.',
        insight: 'The key conceptual shift: stop thinking about knowledge (what a system knows) and start thinking about structure (how a system is organized). Two systems can have completely different content but identical structure — and that structure is what transfers.',
      },
      concepts: [
        {
          title: 'Graph Isomorphism and Structural Similarity',
          explanation: 'Two graphs are isomorphic if there exists a mapping between their nodes that preserves all edge relationships. Structural intelligence theory asks a softer version: are these two systems approximately isomorphic in a meaningful sense? Spectral graph theory provides tools — eigenvalues of the graph Laplacian capture structural properties that are invariant to node labeling. Similar eigenvalue spectra suggest similar structural organization.',
        },
        {
          title: 'Invariants Across Transformations',
          explanation: 'An invariant is a property that remains unchanged under a class of transformations. In physics, conservation of energy is invariant under time translation. In structural intelligence, we seek properties invariant under domain relabeling — properties that describe how a system is organized rather than what it contains. Candidates: degree distribution, clustering coefficient, average path length, entropy of information flow.',
        },
        {
          title: 'Category Theory as a Unification Language',
          explanation: 'Category theory studies structure-preserving mappings (functors) between mathematical structures (categories). It provides a formal language for asking: "what structure is preserved when I map from domain A to domain B?" A functor between two intelligence categories preserves the structural relationships that matter — making explicit what ERP-X is actually doing mathematically. This is the theoretical foundation for a rigorous transfer operator.',
        },
        {
          title: 'Dynamical Systems and Attractor Landscapes',
          explanation: 'Any intelligent system evolves over time — learning, adapting, converging. Dynamical systems theory describes this evolution in terms of attractors (stable states), basins of attraction (regions converging to each state), and phase transitions (sudden changes in system organization). Structural intelligence theory proposes that equivalent attractors and basin geometries across different domains indicate transferable structural intelligence.',
        },
        {
          title: 'Information Geometry of Intelligence',
          explanation: 'Information geometry studies probability distributions as points on a curved manifold, using the Fisher information metric. Learning in a neural network is motion on this manifold. Structural intelligence theory asks: do systems in different domains trace similar geodesics on their respective information manifolds? If so, their learning dynamics share geometric structure — and that geometry can be mapped between domains.',
        },
        {
          title: 'Topology-Preserving Encodings',
          explanation: 'A topology-preserving encoding maps a complex system into a representation space such that structural relationships are maintained. Two systems with similar topological structure should map to nearby regions of the encoding space. This is the basis for the structural embeddings that ERP-X\'s mapping operator will use: encode both domains into a shared structural space, then transfer in that space.',
        },
      ],
      milestones: [
        { year: '2026', event: 'First paper formalizing cross-domain structural invariants using spectral graph theory' },
        { year: '2027', event: 'Universal graph schema v1 — a domain-agnostic representation supporting 5+ domains' },
        { year: '2028', event: 'First empirical demonstration: structural embedding trained on ecosystems improves economic agent modeling' },
        { year: '2029', event: 'Category theory formalization of structural intelligence — first rigorous transfer operator definition' },
        { year: '2030', event: 'Structural Intelligence Theory paper published in Nature Machine Intelligence' },
        { year: '2031', event: 'Invariant detection system v1 — automated discovery of structural invariants across domain pairs' },
      ],
      research: {
        foundationalPapers: [
          { title: 'Graph Neural Networks: A Review of Methods and Applications', authors: 'Zhou et al.', year: 2020, significance: 'GNNs are the primary tool for structural encoding — essential Stage 03 prerequisite' },
          { title: 'Spectral Graph Theory', authors: 'Chung', year: 1997, significance: 'Eigenvalue methods for graph structural analysis — the mathematical core of invariant detection' },
          { title: 'A Primer on Category Theory for Computer Scientists', authors: 'Barr & Wells', year: 1990, significance: 'The formal language for describing structure-preserving mappings between domains' },
        ],
        keyInsight: 'The breakthrough realization: what makes two intelligent systems similar is not their content but their structural organization — the topology of their information flow, the geometry of their optimization landscapes, and the patterns of their emergent dynamics.',
        openQuestion: 'Can structural invariants be detected automatically, or does their identification require human insight? Stage 05\'s ERP-SIM will test this computationally.',
      },
      buildPath: [
        { step: 1, title: 'Study Structural Mathematics', goal: 'Build required mathematical foundation', tasks: ['Master spectral graph theory — graph Laplacian, eigenvalues, Cheeger constant', 'Study dynamical systems: attractors, bifurcations, phase portraits', 'Introduction to category theory: objects, morphisms, functors, natural transformations'] },
        { step: 2, title: 'Implement Structural Encoders', goal: 'Domain-agnostic system representation', tasks: ['Build a graph neural network that encodes any system as a structural embedding', 'Test on 3 domain pairs: ecosystem network, market network, social network', 'Measure structural similarity between systems using embedding distances'] },
        { step: 3, title: 'Build an Invariant Detection System', goal: 'Automated structure discovery', tasks: ['Compute degree distribution, clustering coefficient, path length across domain pairs', 'Build a classifier that predicts whether two systems are structurally similar', 'Identify which structural features are most predictive of domain transfer success'] },
      ],
    },
  },
  {
    id: 5,
    number: '04',
    title: 'ERP-X Cross-Domain Intelligence',
    years: '2028 – 2035',
    breakthrough: 'Knowledge Transfer Across Realities',
    abbrev: 'ERP-X',
    color: 'pink',
    accent: '#ec4899',
    bg: 'from-pink-950/80 to-pink-900/40',
    border: 'border-pink-500/40',
    badge: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    dot: 'bg-pink-500',
    icon: '🔀',
    coreCapability: 'Identify structures in one domain, transfer them to another, preserve critical invariants.',
    coreFormula: 'T(A → B) = φ(structure_A → structure_B)',
    erpxComponents: ['Structural Encoder', 'Invariant Extractor', 'Mapping Operator', 'Transfer Evaluator'],
    transferExamples: ['Ecosystem dynamics → Multi-agent resource allocation', 'Chemistry learning rules → Neural adaptation', 'Climate optimization → Strategy planning'],
    leadingOrgs: ['OpenAI Research', 'Google DeepMind', 'FAIR Meta AI', 'Stanford HAI'],
    validationRequired: 'Measurable transfer: prediction improvement, adaptation acceleration, reasoning generalization.',
    gap: 'ERP-X works for limited domain pairs — generalized transfer across arbitrary domains requires ERP-SIM validation.',
    leadsTo: 'ERP-SIM Simulation Science',
    detail: {
      overview: {
        summary: 'ERP-X is the most ambitious and hardest component of the UTI program. It is a system that can take structural knowledge learned in one domain and apply it in another — not just superficially, but in a way that measurably improves performance. A system trained on ecosystem competition dynamics should become better at modeling market competition dynamics, even though it has never seen market data. This is cross-domain structural transfer.',
        why: 'The EEI stage proves that structured knowledge helps within a domain. Stage 03 proves that structural invariants exist across domains. ERP-X is the engineering challenge of building a system that actually performs the transfer. The transfer operator T(A→B) must encode the structure of domain A, identify its invariants, map those invariants to domain B\'s representation, and inject the transferred structure into domain B\'s reasoning system.',
        significance: 'If ERP-X works, it would represent a fundamental breakthrough in AI: a system that learns from one reality and becomes more capable in a different reality. This is qualitatively different from transfer learning in ML (same data modality, similar distribution). ERP-X transfer operates at the structural level — the topology and dynamics of the systems, not their content.',
        insight: 'The mathematical challenge: T(A→B) must preserve invariants while discarding domain-specific content. The engineering challenge: measuring whether transfer actually occurred and whether it improved performance.',
      },
      concepts: [
        {
          title: 'The Transfer Operator T(A → B)',
          explanation: 'The core of ERP-X is a formal transfer operator: given a representation of system A and a target domain B, produce a structural initialization for domain B that incorporates what was learned in A. Formally: T(A→B) = φ(encode(A) → decode_B). The encoder is domain-agnostic (Stage 03\'s structural encoder). The decoder maps the structural representation into domain B\'s native representation space.',
        },
        {
          title: 'Structural Encoder and Domain-Agnostic Representation',
          explanation: 'The structural encoder takes any intelligent system as input (regardless of domain) and produces a domain-agnostic vector representation. This representation captures topological, dynamical, and information-geometric properties — not domain content. Two structurally similar systems from different domains should produce similar encodings. This is implemented as a graph neural network with structural featurization.',
        },
        {
          title: 'Invariant Extractor and Preservation Checking',
          explanation: 'Before transferring, the system identifies which invariants of domain A should be preserved in domain B. Not all structural properties are relevant — a competition network\'s degree distribution might transfer, but its specific resource quantities certainly don\'t. The invariant extractor uses the Stage 03 catalog of known cross-domain invariants and selects the relevant subset for the specific A→B mapping.',
        },
        {
          title: 'Mapping Operator and Representation Alignment',
          explanation: 'The mapping operator aligns the structural representation of domain A with the native representation space of domain B. This is analogous to domain adaptation in ML, but operating on structural rather than content representations. Techniques: optimal transport (finding the minimum-cost mapping between distributions), cycle-consistency constraints (if A→B→A should return to the original), and manifold alignment (aligning the geometric structure of two representation spaces).',
        },
        {
          title: 'Transfer Evaluator and Measurability Requirement',
          explanation: 'This is the scientific validation requirement: ERP-X must produce measurable improvement. The transfer evaluator runs controlled experiments: (1) train domain B with standard initialization; (2) train domain B with ERP-X structural initialization from domain A; (3) compare performance on domain B tasks. Without measurable improvement, ERP-X is not science — it\'s metaphor.',
        },
        {
          title: 'Loss-of-Reality and Transfer Fidelity',
          explanation: 'Not all structural information survives domain transfer. "Loss of reality" is the structural degradation that occurs when mapping from domain A to domain B — analogous to information loss in compression. The transfer fidelity metric measures how much of the original structure was preserved through the mapping. High fidelity transfer preserves critical invariants; low fidelity indicates the domains are structurally incompatible for this mapping.',
        },
      ],
      milestones: [
        { year: '2028', event: 'First working ERP-X transfer: ecosystem competition dynamics improve economic agent modeling by measurable margin' },
        { year: '2029', event: 'ERP-X v1 paper: "Cross-Domain Structural Transfer for Intelligent Systems"' },
        { year: '2030', event: 'ERP-X validates transfer across 5 domain pairs with consistent improvement on benchmarks' },
        { year: '2031', event: 'Transfer operator formalized mathematically using optimal transport theory' },
        { year: '2032', event: 'ERP-X generalized to n-domain transfer — simultaneous structural initialization from multiple source domains' },
        { year: '2033', event: 'ERP-X applied in scientific discovery — chemistry knowledge improves climate model initialization' },
        { year: '2035', event: 'ERP-X integrated into EEI systems — epistemic agents with cross-domain structural memory' },
      ],
      research: {
        foundationalPapers: [
          { title: 'Optimal Transport for Domain Adaptation', authors: 'Courty et al.', year: 2017, significance: 'Mathematical framework for mapping between domain distributions — foundation of the mapping operator' },
          { title: 'Transfer Learning with Deep Networks', authors: 'Pan & Yang', year: 2010, significance: 'Foundational transfer learning survey — ERP-X extends this from content to structural transfer' },
          { title: 'Cycle-Consistent Adversarial Networks', authors: 'Zhu et al.', year: 2017, significance: 'Cycle consistency as a constraint for structure-preserving mappings between domains' },
        ],
        keyInsight: 'ERP-X fails if it confuses structural similarity with content similarity. Two domains can have identical content and different structure (both about "competition" but organized differently) or identical structure and different content (ecosystem and market: different content, similar structure). ERP-X must operate on structure alone.',
        openQuestion: 'What is the minimum structural similarity required for productive transfer? Below a threshold, does ERP-X hurt more than it helps?',
      },
      buildPath: [
        { step: 1, title: 'Implement the Structural Encoder', goal: 'Domain-agnostic representation', tasks: ['Train a GNN on 3 structurally diverse domains simultaneously', 'Verify that structurally similar domains cluster in the encoding space', 'Measure inter-domain structural similarity using encoding distance'] },
        { step: 2, title: 'Build the Mapping Operator', goal: 'Cross-domain structural alignment', tasks: ['Implement optimal transport between structural encoding distributions', 'Add cycle-consistency loss: T(A→B)→A should recover A\'s structure', 'Test on ecosystem → economic domain pair'] },
        { step: 3, title: 'Run Controlled Transfer Experiments', goal: 'Scientific validation', tasks: ['Design 3 controlled experiments with baseline and ERP-X conditions', 'Measure: does ERP-X structural initialization improve performance on domain B tasks?', 'Publish negative results too — failed transfers reveal structural incompatibility'] },
      ],
    },
  },
  {
    id: 6,
    number: '05',
    title: 'ERP-SIM Simulation Science',
    years: '2030 – 2036',
    breakthrough: 'Theory Becomes Experimentally Testable',
    abbrev: 'ERP-SIM',
    color: 'teal',
    accent: '#14b8a6',
    bg: 'from-teal-950/80 to-teal-900/40',
    border: 'border-teal-500/40',
    badge: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    dot: 'bg-teal-500',
    icon: '🧪',
    purpose: 'Create synthetic universes where intelligence emerges, systems evolve, and transfer is measurable.',
    simulationLayers: ['Agent Systems', 'Dynamic Environments', 'Learning Rules', 'Intelligence Metrics', 'Emergence Detection'],
    analogies: ['Particle accelerators for physics → ERP-SIM as intelligence accelerator', 'Computational biology → Computational intelligence science'],
    researchOutputs: ['Synthetic Universe Experiments', 'Phase Transition Validation', 'Cross-domain Transfer Benchmarks'],
    leadingOrgs: ['NVIDIA Research', 'Google Cloud AI', 'Anthropic Long-Horizon', 'MIT Media Lab'],
    gap: 'Simulation covers 2–3 domains — full multi-scale cross-reality simulation requires CSIM metrics and massive compute.',
    leadsTo: 'CSIM Universal Metrics',
    detail: {
      overview: {
        summary: 'ERP-SIM transforms UTI from a theoretical framework into an experimental science. Just as particle accelerators let physicists test quantum theories by creating controlled high-energy environments, ERP-SIM creates synthetic computational universes where intelligence can be made to emerge, evolve, and transfer under controlled conditions. For the first time, hypotheses about cross-domain transfer can be tested experimentally rather than just argued theoretically.',
        why: 'Theory alone cannot validate ERP-X or structural intelligence. Real-world systems are too entangled — too many confounding variables, no way to control the experiment. ERP-SIM provides clean experimental conditions: define the structural rules of a synthetic universe, introduce agents that must adapt and learn, and observe whether intelligence emerges and transfers according to UTI predictions.',
        significance: 'ERP-SIM elevates UTI to a scientific discipline. Papers with ERP-SIM results are falsifiable — they make specific predictions about intelligence emergence under defined conditions, and experiments either confirm or refute those predictions. This is what separates UTI from speculative philosophy and makes it publishable in Nature or Science.',
        insight: '"ERP-SIM is an accelerator for intelligence science." Just as particle accelerators don\'t wait for natural high-energy events, ERP-SIM doesn\'t wait for natural intelligence evolution — it creates controlled environments where specific intelligence phenomena can be induced and measured.',
      },
      concepts: [
        {
          title: 'Synthetic Universe Design',
          explanation: 'A synthetic universe is a computational environment with defined physical laws, energy/resource constraints, and agent interaction rules. The designer controls: what information agents can sense, what actions they can take, what resources they must compete for or cooperate around, and what the fitness function (selection pressure) is. By varying these parameters systematically, ERP-SIM can induce different forms of intelligence and observe structural signatures.',
        },
        {
          title: 'Agent-Based Intelligence Modeling',
          explanation: 'Agents in ERP-SIM are minimal intelligent units: they perceive state, learn from experience, and take actions to maximize their fitness. The key design choice is the learning rule — how agents update their behavior based on outcomes. ERP-SIM tests whether identical learning rules produce structurally similar intelligence across different synthetic domains, which would confirm Stage 03\'s structural invariants hypothesis.',
        },
        {
          title: 'Emergence Detection and Phase Transitions',
          explanation: 'Emergence is the appearance of collective behavior that is not reducible to individual agent behavior. ERP-SIM monitors for phase transitions — sudden changes in collective intelligence signatures as system parameters cross thresholds. Detecting emergence computationally requires measuring collective information processing, coordination patterns, and adaptive efficiency. Phase transitions in ERP-SIM correspond to the emergence of new intelligence capabilities.',
        },
        {
          title: 'Cross-Domain Transfer Experiments in Simulation',
          explanation: 'The killer experiment: train agents in synthetic universe A until they develop adaptive intelligence. Then transfer their structural knowledge (via ERP-X) to agents in synthetic universe B with completely different domain parameters. Do the transferred agents adapt faster and reach higher performance than agents initialized without transfer? Positive results provide the first controlled validation of ERP-X.',
        },
        {
          title: 'Multi-Domain Simulation Architecture',
          explanation: 'ERP-SIM must run multiple synthetic universes simultaneously, with controlled inter-universe connections. Universe A might simulate ecosystem competition; Universe B simulates economic exchange; Universe C simulates cognitive problem-solving. Each universe has its own laws and agents, but they share a structural representation layer that ERP-X can access to perform cross-universe transfer experiments.',
        },
        {
          title: 'Compute Requirements and Simulation Scale',
          explanation: 'Running meaningful ERP-SIM experiments requires significant compute: millions of agent-steps per experiment, thousands of experimental conditions, and multiple parallel universes. GPU clusters are minimum viable; TPU pods and distributed compute are required for production ERP-SIM. This is not a laptop experiment — it requires dedicated research infrastructure, analogous to physics simulation clusters.',
        },
      ],
      milestones: [
        { year: '2030', event: 'ERP-SIM v1: first multi-domain simulation supporting ecosystem, economic, and agent-learning universes' },
        { year: '2031', event: 'First controlled emergence experiment — phase transition in collective intelligence detected and characterized' },
        { year: '2032', event: 'First ERP-X validation in simulation: cross-domain transfer measurably accelerates adaptation in Universe B' },
        { year: '2033', event: 'ERP-SIM scales to 5 synthetic universes — consistent cross-domain transfer effects across all pairs' },
        { year: '2034', event: 'Intelligence emergence paper published in Nature — "Intelligence as Phase Transitions in Complex Adaptive Systems"' },
        { year: '2035', event: 'ERP-SIM open-sourced as research platform — multiple university groups begin independent experiments' },
        { year: '2036', event: 'ERP-SIM v2: quantum-inspired synthetic universes extending simulation to sub-classical information dynamics' },
      ],
      research: {
        foundationalPapers: [
          { title: 'Complex Adaptive Systems', authors: 'Holland', year: 1992, significance: 'Foundational framework for agent-based modeling of intelligence emergence' },
          { title: 'Mesa: Agent-Based Modeling in Python', authors: 'Masad & Kazil', year: 2015, significance: 'Practical agent-based simulation framework — the technical starting point for ERP-SIM' },
          { title: 'Intelligence as Information Processing', authors: 'Hutter', year: 2005, significance: 'AIXI formalization — the theoretical baseline ERP-SIM measures against' },
        ],
        keyInsight: 'ERP-SIM\'s defining contribution is making intelligence science experimental. The hypothesis "ERP-X transfers structural intelligence across domains" becomes falsifiable when tested in controlled synthetic universes with measurable performance outcomes.',
        openQuestion: 'Do intelligence emergence thresholds (phase transitions) depend only on structural parameters, or on domain-specific content too? If structural, then CSIM metrics (Stage 06) can be defined universally.',
      },
      buildPath: [
        { step: 1, title: 'Build a Single Synthetic Universe', goal: 'ERP-SIM proof of concept', tasks: ['Implement an ecosystem simulation with competing agents using Mesa or NetLogo', 'Add a learning rule: agents that find resources more efficiently reproduce more', 'Measure intelligence metrics: collective adaptation rate, information efficiency'] },
        { step: 2, title: 'Add a Second Universe and Transfer Channel', goal: 'First cross-domain experiment', tasks: ['Build a second synthetic universe with different domain parameters (e.g., economic exchange)', 'Implement ERP-X structural encoder to extract structure from Universe A', 'Initialize Universe B agents with transferred structure; measure adaptation vs baseline'] },
        { step: 3, title: 'Run Systematic Transfer Experiments', goal: 'Publishable validation', tasks: ['Design 10+ controlled experiments varying structural similarity between universes', 'Measure: does higher structural similarity predict better transfer performance?', 'Publish: "ERP-X Cross-Domain Transfer Validated in Synthetic Universe Experiments"'] },
      ],
    },
  },
  {
    id: 7,
    number: '06',
    title: 'CSIM Universal Intelligence Metrics',
    years: '2032 – 2042',
    breakthrough: 'Measure Intelligence Across Any Substrate',
    abbrev: 'CSIM',
    color: 'emerald',
    accent: '#10b981',
    bg: 'from-emerald-950/80 to-emerald-900/40',
    border: 'border-emerald-500/40',
    badge: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    dot: 'bg-emerald-500',
    icon: '📊',
    coreProblem: 'Current AI metrics are domain-specific. UTI requires substrate-independent metrics that work across AI, biology, organizations, ecosystems, and synthetic agents.',
    candidateMetrics: ['Compression Efficiency', 'Causal Depth Index', 'Transfer Capability Score', 'Adaptability Coefficient', 'Self-Model Quality', 'Robustness Under Constraint'],
    substrates: ['AI Systems', 'Biological Organisms', 'Organizations', 'Ecosystems', 'Synthetic Agents'],
    leadingOrgs: ['Santa Fe Institute', 'Allen Institute for AI', 'DeepMind Evaluation'],
    gap: 'Universal metrics validated for 3–5 substrates — cosmic and quantum-scale substrates remain untested.',
    leadsTo: 'Multi-Scale Intelligence Unification',
    detail: {
      overview: {
        summary: 'CSIM tackles the measurement problem at the heart of UTI: how do you measure intelligence across fundamentally different substrates? An AI benchmark (MMLU, HumanEval) doesn\'t apply to an ecosystem or a governance system. A biological fitness metric doesn\'t apply to an LLM. CSIM develops universal metrics that capture core properties of intelligence regardless of substrate: compression efficiency, causal depth, transfer capability, and adaptability.',
        why: 'Without universal metrics, UTI cannot be falsified. "This system is more intelligent" has no meaning without a scale. CSIM provides that scale — defining what "intelligent" means formally, measuring it consistently, and allowing comparison across substrates. This is analogous to what thermodynamics did for heat: gave it a precise, substrate-independent definition (average kinetic energy) that enabled consistent measurement and comparison.',
        significance: 'CSIM is the scientific validation layer of UTI. Every claim about intelligence — that system A is more intelligent than system B, that ERP-X improved intelligence, that intelligence emerged at a particular simulation condition — must be grounded in CSIM metrics. Without CSIM, UTI is philosophy; with CSIM, it is science.',
        insight: 'Intelligence is defined by what a system does with information — not by what substrate it runs on. CSIM measures the doing, not the substrate.',
      },
      concepts: [
        {
          title: 'Compression Efficiency as Intelligence Metric',
          explanation: 'A fundamental property of intelligence is its ability to find compact representations of complex phenomena. An intelligent system learns that "all swans I\'ve seen are white" — compressing many observations into one rule. Compression efficiency measures how much a system reduces the description length of its environment through learning. More intelligent systems achieve higher compression. This applies equally to LLMs (perplexity), ecosystems (species diversity encoding environmental complexity), and organizations (standard operating procedures).',
        },
        {
          title: 'Causal Depth Index',
          explanation: 'Causal depth measures how deeply a system understands causal structure — distinguishing correlation from causation and modeling multi-level causal chains. A shallow system knows "A correlates with B." A deep system knows "A causes C, which causes B, but only when D is present." CSIM\'s causal depth index measures the maximum causal chain length a system reliably encodes and reasons over. This is substrate-independent: applies to AI systems, ecosystem food webs, and organizational decision chains.',
        },
        {
          title: 'Transfer Capability Score',
          explanation: 'Transfer capability directly measures ERP-X\'s key prediction: how much knowledge learned in domain A improves performance in domain B. The Transfer Capability Score measures the gradient of improvement: how quickly does domain B performance improve after receiving structural knowledge from domain A? A high TCS indicates strong structural compatibility and successful ERP-X transfer. This metric makes Stage 04\'s key claims quantitatively falsifiable.',
        },
        {
          title: 'Adaptability Coefficient',
          explanation: 'Adaptability measures how quickly and efficiently a system adjusts to environmental change. This is critical for UTI because adaptation is a core property of intelligence across all substrates. The adaptability coefficient is measured by introducing a controlled perturbation (changing the environment) and measuring recovery time, final performance, and energy/resource cost of adaptation. Higher adaptability = higher intelligence, independent of domain.',
        },
        {
          title: 'Self-Model Quality',
          explanation: 'Intelligence requires a model of the self — knowing what you know, what you don\'t know, and what you can do. Self-model quality measures the accuracy of a system\'s internal representation of its own capabilities and limitations. For AI: calibration (does confidence correlate with accuracy?). For ecosystems: niche specialization (does each species accurately exploit its comparative advantage?). For organizations: strategic clarity (does the org structure match the environment it operates in?).',
        },
        {
          title: 'Robustness Under Constraint',
          explanation: 'Intelligence is not just about performance in ideal conditions — it is about maintaining capability under resource constraints, adversarial conditions, and uncertainty. The robustness metric measures performance degradation as available resources (compute, energy, time) are progressively reduced. More intelligent systems degrade more gracefully — they maintain core capabilities longer as resources shrink.',
        },
      ],
      milestones: [
        { year: '2032', event: 'CSIM v1 published: 6 universal metrics formally defined and measured on 3 substrates (AI, ecosystem, organization)' },
        { year: '2033', event: 'CSIM benchmark suite: standard test battery for measuring UTI metrics across substrate types' },
        { year: '2034', event: 'First cross-substrate intelligence comparison: AI system vs biological organism vs synthetic agent' },
        { year: '2035', event: 'CSIM adopted by 3 independent research groups — inter-lab reproducibility confirmed' },
        { year: '2037', event: 'CSIM extended to governance systems: political institutions measured on universal intelligence metrics' },
        { year: '2040', event: 'CSIM v2: 12 metrics, validated across 8 substrates including synthetic universes from ERP-SIM' },
        { year: '2042', event: 'CSIM accepted as the standard measurement framework for Stage 07 multi-scale analysis' },
      ],
      research: {
        foundationalPapers: [
          { title: 'A Formal Theory of Inductive Inference', authors: 'Solomonoff', year: 1964, significance: 'Algorithmic complexity as a universal measure of compression — the theoretical ancestor of CSIM' },
          { title: 'Universal Intelligence: A Definition of Machine Intelligence', authors: 'Legg & Hutter', year: 2007, significance: 'First formal substrate-independent definition of intelligence — CSIM operationalizes this' },
          { title: 'Measuring Intelligence in Systems', authors: 'Multiple', year: 'ongoing', significance: 'Active research area — CSIM synthesizes and extends existing approaches' },
        ],
        keyInsight: 'Intelligence is not task performance — it is the capacity for adaptive compression, causal reasoning, and structural transfer across environments. CSIM measures this capacity, not task-specific outcomes.',
        openQuestion: 'Are CSIM metrics truly independent, or do they all measure aspects of a single underlying quantity? If they collapse to one dimension, that dimension would be the definition of intelligence itself.',
      },
      buildPath: [
        { step: 1, title: 'Implement Compression Efficiency', goal: 'First CSIM metric', tasks: ['For AI: measure perplexity improvement per parameter on held-out distributions', 'For ecosystems: measure species diversity as compression of environmental complexity', 'Compute metric on both substrates and verify it is genuinely substrate-independent'] },
        { step: 2, title: 'Build Causal Depth Measurement', goal: 'Second CSIM metric', tasks: ['Implement causal discovery algorithms (PC algorithm, GES, NOTEARS)', 'Measure maximum causal chain depth in AI system knowledge graphs', 'Compare to biological food web causal depth and organizational decision chains'] },
        { step: 3, title: 'Create CSIM Benchmark Suite', goal: 'Reproducible measurement platform', tasks: ['Build a standardized test battery for all 6 CSIM metrics', 'Test on 3 substrate types with controlled complexity levels', 'Publish as open benchmark: "CSIM: Universal Intelligence Metrics Benchmark"'] },
      ],
    },
  },
  {
    id: 8,
    number: '07',
    title: 'Multi-Scale Intelligence Unification',
    years: '2035 – 2045',
    breakthrough: 'Connect Micro ↔ Macro Intelligence',
    abbrev: null,
    color: 'indigo',
    accent: '#6366f1',
    bg: 'from-indigo-950/80 to-indigo-900/40',
    border: 'border-indigo-500/40',
    badge: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    dot: 'bg-indigo-500',
    icon: '🔭',
    scaleHierarchy: [
      { scale: 'Molecular', example: 'Chemistry' },
      { scale: 'Neural', example: 'Cognition' },
      { scale: 'Agent', example: 'AI Systems' },
      { scale: 'Collective', example: 'Societies' },
      { scale: 'Planetary', example: 'Climate & Governance' },
    ],
    discoveryGoals: ['Recurring Laws Across Scales', 'Scaling Behaviors', 'Emergent Phase Transitions', 'Cross-scale Invariants'],
    leadingOrgs: ['CERN AI Division', 'NASA Computational Intelligence', 'Max Planck Institute', 'Broad Institute'],
    gap: 'Cosmic-scale integration (CE-ERP) and quantum consciousness layers remain open research frontiers.',
    leadsTo: 'Universal Theory of Intelligence',
    detail: {
      overview: {
        summary: 'Stage 07 asks whether the same intelligence principles that operate at the molecular scale (chemical information processing) also operate at the neural scale (cognitive reasoning), the agent scale (AI systems), the collective scale (societies), and the planetary scale (climate-governance interactions). If universal scaling laws govern intelligence across these levels, then UTI is not just a theory for AI — it is a theory for intelligence everywhere.',
        why: 'Stages 03–06 demonstrate that structural invariants exist between domains at similar scales. Stage 07 extends this vertically: do invariants span scales? Physics provides examples: thermodynamics emerges from statistical mechanics; fluid dynamics emerges from molecular dynamics. Stage 07 asks if similar emergence relationships exist in intelligence — if collective intelligence emergence from individual cognitive processes follows universal laws.',
        significance: 'Multi-scale unification is the bridge from ERP-X (cross-domain, same scale) to UTI (cross-scale). It provides the framework for understanding how intelligence at one scale creates the substrate for intelligence at the next scale. This is the deepest conceptual contribution of the UTI program — explaining emergence hierarchically rather than just cataloging it.',
        insight: 'Intelligence may not just be a property of systems — it may be a property of scales. The same system can exhibit different forms of intelligence depending on the scale at which it is observed.',
      },
      concepts: [
        {
          title: 'Renormalization Groups and Scale Invariance',
          explanation: 'Renormalization group (RG) theory in physics describes how physical laws transform as you change the observation scale. Fixed points of the RG flow are scale-invariant — the physics looks the same at all scales. Stage 07 applies RG thinking to intelligence: what intelligence laws are preserved as we move from molecular to neural to collective scales? Scale-invariant intelligence laws would be the deepest discoveries of the UTI program.',
        },
        {
          title: 'Scaling Laws Across Intelligence Scales',
          explanation: 'Just as neural network performance scales as a power law with compute, Stage 07 asks: does collective intelligence scale as a power law with the number and quality of individual intelligences composing it? Does molecular information processing efficiency scale predictably with molecular complexity? Finding these scaling laws would unify intelligence science in the same way that scaling laws unified thermodynamics.',
        },
        {
          title: 'Emergence as a Cross-Scale Mechanism',
          explanation: 'Emergence is the mechanism by which intelligence at one scale creates the substrate for intelligence at the next. Individual neurons → collective cognition. Individual cognitions → social intelligence. Individual societies → civilizational intelligence. Stage 07 formalizes this emergence hierarchy: what properties of the lower scale are necessary and sufficient for intelligence to emerge at the higher scale?',
        },
        {
          title: 'Cross-Scale CSIM Metrics',
          explanation: 'CSIM metrics (Stage 06) were defined for systems at a single scale. Stage 07 requires extending CSIM to cross-scale measurement: how does compression efficiency at the molecular scale predict compression efficiency at the neural scale? Do causal depth relationships at the agent scale predict collective intelligence at the societal scale? Cross-scale CSIM metrics are the empirical tools for testing multi-scale unification.',
        },
        {
          title: 'Hierarchical Intelligence Graphs',
          explanation: 'Stage 07 proposes representing intelligence across all scales as a hierarchical graph where nodes at each level aggregate into nodes at the next level. The structure of this hierarchy — which scale-level properties aggregate into higher-level properties — encodes the emergence relationships. Universal intelligence patterns that appear at every level of the hierarchy are the deepest structural invariants of UTI.',
        },
      ],
      milestones: [
        { year: '2035', event: 'First paper connecting molecular information processing to neural intelligence using RG-inspired analysis' },
        { year: '2037', event: 'Scaling laws for collective intelligence: performance vs population size follows power law over 3 orders of magnitude' },
        { year: '2038', event: 'Hierarchical intelligence graph: first formal model spanning molecular → neural → agent → collective scales' },
        { year: '2040', event: 'Cross-scale CSIM validated: lower-scale metrics predict higher-scale intelligence outcomes' },
        { year: '2042', event: 'Multi-scale UTI paper: "Universal Scaling Laws for Intelligence Across Biological and Artificial Systems"' },
        { year: '2044', event: 'First practical application: planetary-scale governance models initialized with molecular-scale learning principles' },
        { year: '2045', event: 'Multi-scale unification framework adopted as Stage 08 UTI mathematical foundation' },
      ],
      research: {
        foundationalPapers: [
          { title: 'More is Different', authors: 'Philip Anderson', year: 1972, significance: 'Seminal paper on emergence — why higher-level phenomena cannot be reduced to lower-level descriptions' },
          { title: 'Scaling Laws for Neural Language Models', authors: 'Kaplan et al.', year: 2020, significance: 'Demonstrates power-law scaling in AI — Stage 07 asks if this extends across biological scales' },
          { title: 'Statistical Physics of Self-Replication', authors: 'England', year: 2013, significance: 'Physics of intelligent adaptation at molecular scale — the bottom of the UTI scale hierarchy' },
        ],
        keyInsight: 'If scaling laws for intelligence are universal across scales, then a single equation might describe intelligence emergence from chemistry to civilization. That equation would be the UTI.',
        openQuestion: 'Are intelligence scaling laws truly universal, or do they break at some scales? Identifying the scale where universality fails would reveal the boundaries of the UTI\'s validity.',
      },
      buildPath: [
        { step: 1, title: 'Implement Cross-Scale Measurement', goal: 'Measure intelligence at 3+ scales simultaneously', tasks: ['Select test systems at molecular, neural, and agent scales', 'Apply CSIM metrics at each scale', 'Plot CSIM metrics vs scale — look for power-law relationships'] },
        { step: 2, title: 'Build a Hierarchical Intelligence Model', goal: 'Formal emergence representation', tasks: ['Design a hierarchical graph connecting 3 intelligence scales', 'Implement aggregation functions from lower to higher scale', 'Test: does lower-scale CSIM predict higher-scale CSIM?'] },
        { step: 3, title: 'Identify Cross-Scale Invariants', goal: 'Universal scaling laws', tasks: ['Compute the structural invariants (Stage 03) at each scale independently', 'Test which invariants are preserved across scale transitions', 'Publish the cross-scale invariant catalog — the deepest structural discoveries of the UTI program'] },
      ],
    },
  },
  {
    id: 9,
    number: '08',
    title: 'Universal Theory of Intelligence',
    years: '2040 – 2050+',
    breakthrough: 'Intelligence as a Universal Systems Phenomenon',
    abbrev: 'UTI',
    color: 'rose',
    accent: '#f43f5e',
    bg: 'from-rose-950/80 to-rose-900/40',
    border: 'border-rose-500/40',
    badge: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
    dot: 'bg-rose-500',
    icon: '✨',
    corePrinciple: '"Intelligence is the adaptive compression and transformation of structured information under constraints across evolving systems."',
    legitimacyRequirements: ['Formal Mathematics', 'Testable Predictions', 'Multi-domain Compression', 'Cross-domain Transferability', 'Empirical Reproducibility'],
    publicationVenues: ['Science', 'Nature', 'Physical Review X', 'Nature Machine Intelligence'],
    leadingOrgs: ['OpenAI', 'Anthropic', 'Google DeepMind', 'FAIR Meta AI', 'University Consortiums'],
    analogy: 'UTI is to intelligence systems what calculus is to motion — a unifying mathematical language.',
    gap: 'UTI is validated across physical, biological, and cognitive systems — cosmological scale integration completes in ERP phase.',
    leadsTo: 'Eternal Research Program',
    detail: {
      overview: {
        summary: 'The Universal Theory of Intelligence is the capstone of the previous 8 stages. UTI is not a single insight but a formal framework that unifies everything discovered in Stages 01–07: the information-centric foundation, the epistemic architecture, the structural invariants, the cross-domain transfer operator, the simulation validation, the universal metrics, and the cross-scale laws. UTI expresses all of this in a coherent mathematical formalism that makes falsifiable predictions.',
        why: 'The preceding stages each solved part of the puzzle: how intelligence processes information, how it forms knowledge, what structures it shares across domains, how it transfers, how it emerges, how it scales, how to measure it. UTI integrates all of this into a unified formal theory — analogous to how Maxwell\'s equations unified electricity, magnetism, and light, or how statistical mechanics unified thermodynamics and Newtonian mechanics.',
        significance: 'If UTI achieves the level of formalization and empirical validation to be published in Science or Nature and adopted by multiple independent research groups, it would represent a scientific achievement comparable to the development of quantum mechanics or the Modern Synthesis in biology. It would provide a universal framework for understanding, building, and governing intelligent systems at any scale and in any domain.',
        insight: '"UTI is to intelligence systems what calculus is to motion." It provides a universal language for describing, predicting, and reasoning about intelligence — wherever it appears.',
      },
      concepts: [
        {
          title: 'The UTI Axiom System',
          explanation: 'UTI is grounded in 5 core axioms: (1) Intelligence is substrate-independent — it depends on information structure, not physical medium. (2) Intelligence requires adaptive compression — intelligent systems reduce description complexity through learning. (3) Intelligence exhibits structural invariants across domains — certain organizational patterns are universal to intelligence. (4) Intelligence can transfer structurally — invariant structure learned in one domain improves adaptation in others. (5) Intelligence scales hierarchically — the same principles apply at molecular, cognitive, agent, and collective scales.',
        },
        {
          title: 'The Universal State Equation',
          explanation: 'UTI proposes a universal state equation for intelligent systems: S(t+1) = F(S(t), C(t), I(t)), where S(t) is the system\'s state, C(t) is the constraint set at time t, and I(t) is the information available. F is the adaptive transformation function — the "intelligence" of the system is captured in the properties of F: how efficiently it compresses, how deeply it reasons causally, how well it transfers structural knowledge. Different domains instantiate S, C, I differently — but F\'s structural properties are universal.',
        },
        {
          title: 'Falsifiable UTI Predictions',
          explanation: 'UTI is not a philosophical position — it makes specific, falsifiable predictions: (1) Systems with higher CSIM scores will adapt faster to novel environments. (2) ERP-X transfer between structurally similar domains will produce measurable improvement exceeding 15% on adaptation benchmarks. (3) Intelligence emergence phase transitions will occur at predictable CSIM threshold values in ERP-SIM synthetic universes. (4) Cross-scale CSIM metrics will follow power laws with exponents predictable from the Stage 07 multi-scale framework.',
        },
        {
          title: 'UTI Formalism and Mathematical Structure',
          explanation: 'The full UTI formalism requires: information theory (entropy, compression), graph theory (structural invariants), dynamical systems (state evolution, attractors), category theory (domain-general mappings), information geometry (learning dynamics on probability manifolds), and statistical physics (emergence, phase transitions). UTI is a synthesis — it does not introduce entirely new mathematics, but it provides the first formal integration of these mathematical tools in a single coherent framework for intelligence.',
        },
        {
          title: 'UTI vs Existing Theories',
          explanation: 'UTI differs from existing intelligence theories in scope and integration. AIXI (Hutter) defines intelligence as optimal compression but is incomputable. IIT (Integrated Information Theory) focuses on consciousness but is domain-specific. Universal Turing Computation captures computational universality but not intelligence specifically. UTI is broader than AIXI (includes structural transfer and multi-scale laws), more empirical than IIT (substrate-independent and measurable), and richer than computation theory (includes adaptation, transfer, and emergence).',
        },
      ],
      milestones: [
        { year: '2040', event: 'UTI axiom system formally published — 5 axioms defining universal intelligence' },
        { year: '2041', event: 'Universal state equation empirically validated across 7 domain/substrate types' },
        { year: '2042', event: 'First UTI predictions confirmed: CSIM thresholds predict emergence in ERP-SIM universes' },
        { year: '2044', event: 'UTI published in Science: "A Universal Theory of Intelligence Across Physical, Biological, and Artificial Systems"' },
        { year: '2045', event: 'UTI adopted by 10+ independent research groups; first international UTI research consortium formed' },
        { year: '2047', event: 'UTI applied to governance systems — predicts institutional intelligence collapse conditions' },
        { year: '2050+', event: 'UTI becomes foundational framework for AI safety, governance, and the Eternal Research Program' },
      ],
      research: {
        foundationalPapers: [
          { title: 'Universal Intelligence: A Definition of Machine Intelligence', authors: 'Legg & Hutter', year: 2007, significance: 'The formal intelligence definition UTI builds upon and generalizes' },
          { title: 'Integrated Information Theory 3.0', authors: 'Tononi et al.', year: 2016, significance: 'Formal attempt at substrate-independent intelligence measurement — UTI extends and validates this approach' },
          { title: 'A Mathematical Theory of Communication', authors: 'Shannon', year: 1948, significance: 'The foundational information theory that Stage 00 identified as the seed of UTI — now fully integrated' },
        ],
        keyInsight: 'UTI\'s central claim is not "all intelligent systems are the same." It is "all intelligent systems are organized according to the same structural principles — and those principles can be formally described, measured, and used to improve intelligence in any domain."',
        openQuestion: 'Does UTI predict consciousness? IIT does. UTI as formalized here does not claim to explain subjective experience — only structural organization. Whether consciousness is a special case of UTI intelligence or a separate phenomenon remains the deepest open question.',
      },
      buildPath: [
        { step: 1, title: 'Formalize the Axiom System', goal: 'Mathematically rigorous UTI foundation', tasks: ['Derive the 5 UTI axioms from Stages 01–07 empirical results', 'Check axiom independence: can any be derived from the others?', 'Identify the minimal axiom set that implies all Stage 01–07 discoveries'] },
        { step: 2, title: 'Write Falsifiable Predictions', goal: 'Scientific legitimacy', tasks: ['Derive 10 specific, testable predictions from the UTI axioms', 'Design experiments to test each prediction using ERP-SIM and CSIM', 'Pre-register predictions before running experiments — standard scientific practice'] },
        { step: 3, title: 'Draft the UTI Paper', goal: 'Capstone publication', tasks: ['Structure: Introduction → Axioms → Formalism → Predictions → Experimental Validation → Discussion', 'Target Science or Nature — require multi-domain empirical validation', 'Submit first to workshop venues (NeurIPS, ICML) for community feedback'] },
      ],
    },
  },
  {
    id: 10,
    number: '09',
    title: 'Eternal Research Program',
    years: '2050+',
    breakthrough: 'The Theory Never Truly Ends',
    abbrev: 'ERP',
    color: 'fuchsia',
    accent: '#d946ef',
    bg: 'from-fuchsia-950/80 to-fuchsia-900/40',
    border: 'border-fuchsia-500/40',
    badge: 'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30',
    dot: 'bg-fuchsia-500',
    icon: '♾️',
    permanentLayers: ['Intelligence', 'Representation', 'Transfer', 'Emergence', 'Learning'],
    feedbackLoop: ['Build Systems', 'Test Systems', 'Measure Outcomes', 'Revise Theory', 'Repeat'],
    domainModules: ['EEI (Epistemic)', 'ERP-X (Transfer)', 'ERP-SIM (Simulation)', 'CSIM (Metrics)', 'G-ERP (Governance)', 'CE-ERP (Cosmic)', 'CH-ERP (Chemistry)', 'CL-ERP (Climate)'],
    leadingOrgs: ['Global Research Consortium', 'AI-Native Universities', 'Self-evolving Research Systems'],
    horizon: 'At maturity: frameworks evolve, questions deepen, systems improve, and intelligence co-evolves with theory.',
    gap: null,
    leadsTo: 'Next Frontier',
    detail: {
      overview: {
        summary: 'The Eternal Research Program is the state that UTI reaches when it is validated, adopted, and self-sustaining. It is "eternal" not because it is complete, but because it is designed to evolve indefinitely — new domains are added, existing theories are revised based on new evidence, and intelligence systems themselves contribute to the program\'s advancement. The ERP is modeled on the most successful multi-decade scientific programs: quantum field theory, the Modern Synthesis in biology, general relativity.',
        why: 'Science does not have endpoints — only milestones. The ERP design acknowledges this: UTI Stage 08 is a milestone, not a destination. The framework will be revised, extended to new domains (CE-ERP for cosmic scales, Q-ERP for quantum systems, G-ERP for governance), challenged by anomalies, and deepened by future mathematicians and scientists. ERP is the institutional and intellectual structure that ensures this happens systematically.',
        significance: 'The ERP is the most important structural innovation in the UTI program — more important than any individual discovery. A theory without a self-sustaining research community and institutional infrastructure is a dead theory. The ERP provides the living infrastructure that transforms UTI from a research project into a scientific paradigm.',
        insight: '"The ERP is a research operating system, not a research project." It is the system within which intelligence science is conducted — with defined divisions, permanent questions, feedback loops, and evolutionary mechanisms that allow it to survive and grow across generations of researchers.',
      },
      concepts: [
        {
          title: 'Permanent vs Temporary Layers of ERP',
          explanation: 'The ERP separates permanent and temporary components. Permanent: the core questions (What is intelligence? How is knowledge represented? What invariants survive transformation?), the permanent research pillars (representation, transfer, emergence, learning), and the measurement infrastructure (CSIM metrics). Temporary: current models, current tooling, current architectures. Permanent layers survive technology shifts; temporary layers evolve continuously.',
        },
        {
          title: 'The Living Roadmap and Versioned Evolution',
          explanation: 'The ERP maintains a living roadmap that evolves based on results. Each major experimental outcome triggers a roadmap update: confirmed predictions extend the horizon, refuted predictions trigger theory revision, anomalous results open new research divisions. The roadmap is versioned — ERP v1, v2, v3 — with each version reflecting the current state of validated UTI theory. This prevents dogmatism while maintaining cumulative progress.',
        },
        {
          title: 'Domain Module Architecture',
          explanation: 'The ERP is modular: each domain (chemistry, governance, climate, cosmic scales) has its own ERP module (CH-ERP, G-ERP, CL-ERP, CE-ERP). Domain modules share the core UTI framework (common representation, CSIM metrics, ERP-X transfer operator) but have domain-specific instantiations. New domains are added by implementing the domain module interface — an architectural choice that keeps the ERP open to infinite extension.',
        },
        {
          title: 'Self-Evolution Mechanisms',
          explanation: 'At maturity, ERP systems may contribute to their own advancement. AI systems trained on ERP research history could suggest new hypotheses, design experiments, analyze results, and propose theory revisions. This creates a co-evolution dynamic: UTI theory improves intelligence systems, and improved intelligence systems deepen UTI theory. The feedback loop between theory and systems is the engine of ERP self-evolution.',
        },
        {
          title: 'The Research Feedback Loop as Scientific Law',
          explanation: 'ERP institutionalizes the scientific method as a formal loop: Build System → Test System → Measure with CSIM → Revise Theory → Repeat. This loop runs at multiple timescales: rapid iteration (weeks) for prototype experiments, medium-term validation (months) for published results, and long-term theory revision (years) for UTI axiom updates. The loop structure ensures every ERP activity contributes to cumulative knowledge.',
        },
        {
          title: 'Institutional Architecture and Global Consortium',
          explanation: 'The ERP requires institutional infrastructure: a global research consortium with participating universities and labs, open benchmark platforms (CSIM, ERP-SIM), pre-registration for major experiments, open-source research tools, and an editorial process for theory revisions. This infrastructure is modeled on CERN (physics), the Human Genome Project (biology), and the IPCC (climate) — large-scale, multi-institution scientific programs that achieved breakthroughs no single lab could.',
        },
      ],
      milestones: [
        { year: '2050', event: 'ERP founding: global research consortium established with 50+ institutions' },
        { year: '2051', event: 'ERP v1: first versioned UTI framework with 8 domain modules' },
        { year: '2053', event: 'CE-ERP (Cosmic) division activated — cosmological intelligence modeling begins' },
        { year: '2055', event: 'Q-ERP (Quantum) division: quantum information processing integrated into UTI formalism' },
        { year: '2060', event: 'First ERP anomaly: UTI prediction fails in Q-ERP — triggers first major theory revision' },
        { year: '2065', event: 'ERP v2: revised UTI incorporating quantum intelligence — new axiom added' },
        { year: '2075', event: 'ERP operates with 200+ institutions across 50 countries — self-sustaining scientific paradigm' },
        { year: '2100+', event: 'ERP continues indefinitely — intelligence science evolving with civilization' },
      ],
      research: {
        foundationalPapers: [
          { title: 'The Structure of Scientific Revolutions', authors: 'Thomas Kuhn', year: 1962, significance: 'Describes how scientific paradigms form, persist, and are eventually replaced — ERP is designed to be a paradigm' },
          { title: 'Consilience: The Unity of Knowledge', authors: 'E.O. Wilson', year: 1998, significance: 'The intellectual vision that animates ERP: unifying all knowledge under a common framework' },
          { title: 'The Beginning of Infinity', authors: 'David Deutsch', year: 2011, significance: 'The philosophical argument that good explanatory theories are the most powerful human achievement — ERP operationalizes this for intelligence science' },
        ],
        keyInsight: 'The ERP\'s most important insight is that intelligence science, like physics and biology before it, will be an eternal research program — not because it is intractable, but because every answer generates deeper questions, and deeper questions generate richer understanding. The goal is not completion; it is cumulative, self-sustaining progress.',
        openQuestion: 'What is the next question that Stage 09 ERP opens? That is precisely what cannot be known in advance — and that is the definition of an eternal research program.',
      },
      buildPath: [
        { step: 1, title: 'Design the ERP Architecture', goal: 'Institutional and technical blueprint', tasks: ['Define the permanent research questions (5 core questions that never change)', 'Design the domain module interface (how new domains join ERP)', 'Define ERP governance: who can revise UTI axioms, what evidence threshold is required'] },
        { step: 2, title: 'Launch the First Research Loop', goal: 'ERP v1 activation', tasks: ['Pick the smallest complete loop: one EEI experiment → CSIM measurement → theory revision', 'Document the entire loop as a template for future ERP iterations', 'Publish the loop as an ERP methodology paper: "The ERP Research Loop: A Framework for Cumulative Intelligence Science"'] },
        { step: 3, title: 'Build the Open Research Infrastructure', goal: 'Institutional foundation', tasks: ['Open-source CSIM benchmark suite and ERP-SIM platform', 'Create pre-registration system for ERP experiments', 'Establish ERP working groups across 5 universities to begin multi-institution science'] },
      ],
    },
  },
]

export const timelineItems = [
  { years: 'Historical', stage: 'Pre-Foundational', color: '#64748b' },
  { years: '2017–Now', stage: 'Info-Centric', color: '#3b82f6' },
  { years: '2024–2027', stage: 'EEI', color: '#8b5cf6' },
  { years: '2026–2031', stage: 'Structural', color: '#f59e0b' },
  { years: '2028–2035', stage: 'ERP-X', color: '#ec4899' },
  { years: '2030–2036', stage: 'ERP-SIM', color: '#14b8a6' },
  { years: '2032–2042', stage: 'CSIM', color: '#10b981' },
  { years: '2035–2045', stage: 'Multi-Scale', color: '#6366f1' },
  { years: '2040–2050+', stage: 'UTI', color: '#f43f5e' },
  { years: '2050+', stage: 'ERP', color: '#d946ef' },
]
