export const categories = [
  { id: 'uti', label: 'UTI Framework', color: '#8b5cf6', dot: 'bg-violet-500' },
  { id: 'uaif', label: 'UAIF / ELG', color: '#d946ef', dot: 'bg-fuchsia-500' },
  { id: 'intelligence', label: 'Intelligence Science', color: '#f59e0b', dot: 'bg-amber-500' },
  { id: 'ml', label: 'ML Foundations', color: '#0ea5e9', dot: 'bg-sky-500' },
  { id: 'philosophy', label: 'Philosophy of Science', color: '#10b981', dot: 'bg-emerald-500' },
  { id: 'cognitive', label: 'Cognitive Science', color: '#f43f5e', dot: 'bg-rose-500' },
]

export const terms = [
  // ── UTI Framework ──────────────────────────────────────────────────
  {
    id: 'uti',
    term: 'Unified Theory of Intelligence (UTI)',
    category: 'uti',
    short: 'A single mathematical framework describing intelligence across all substrates and scales.',
    definition: 'UTI is the overarching research program to develop a substrate-independent, mathematically rigorous account of intelligence that applies equally to biological brains, AI systems, organizations, and ecosystems. It progresses through 10 stages, from domain-specific pre-foundational work to the fully self-sustaining Eternal Research Program at Stage 09. The central thesis is that all intelligent systems share common representational, computational, and adaptive structures that can be described by a unified formal language.',
    related: ['erp', 'erpx', 'uaif', 'structural-intelligence', 'intelligence-convergence'],
    stageId: null,
  },
  {
    id: 'erp',
    term: 'Eternal Research Program (ERP)',
    category: 'uti',
    short: 'A self-sustaining, community-maintained scientific program designed to evolve indefinitely.',
    definition: 'ERP is Stage 09 of UTI — a Lakatosian research program with a permanent hard core of UTI axioms and an evolving protective belt of domain modules. It is designed to outlive any individual researcher by building institutional infrastructure: open science practices, distributed contribution protocols, and versioned theory documents. The "eternal" descriptor references David Deutsch\'s argument that once a culture of good explanations exists, knowledge can grow without bound.',
    related: ['uti', 'lakatosian-program', 'falsifiability', 'erpsim'],
    stageId: 10,
  },
  {
    id: 'erpx',
    term: 'ERP-X',
    category: 'uti',
    short: 'Substrate-independent information representation unifying cross-domain intelligence.',
    definition: 'ERP-X is the formal information-centric substrate introduced at UTI Stage 01 — a representation layer that expresses intelligence phenomena (learning, memory, adaptation, transfer) independently of the physical or computational medium. It draws on Shannon information theory and structural analogs across biology, economics, and AI. ERP-X is to intelligence what the bit is to communication: a substrate-neutral unit that enables cross-domain formal comparison.',
    related: ['uti', 'structural-intelligence', 'universal-transfer-learning'],
    stageId: 2,
  },
  {
    id: 'erpsim',
    term: 'ERP-SIM',
    category: 'uti',
    short: 'Simulation-based testing framework for UTI predictions.',
    definition: 'ERP-SIM is the computational testbed for UTI Stage 06, providing a controlled simulation environment where multi-domain adaptive intelligence hypotheses can be instantiated, run, and measured. It operationalizes the UTI prediction cycle: theory → simulation → measurement → revision. ERP-SIM bridges the gap between formal theory and empirical validation without requiring full-scale biological or societal experiments.',
    related: ['erp', 'csim', 'dsresearch'],
    stageId: 7,
  },
  {
    id: 'csim',
    term: 'CSIM (Consciousness Substrate Interface Model)',
    category: 'uti',
    short: 'Formal model of the interface between physical substrate and conscious experience.',
    definition: 'CSIM is the theoretical framework at UTI Stage 08 that attempts to formalize the relationship between information processing in a physical substrate and the emergence of subjective experience. It draws on Integrated Information Theory (IIT), Global Workspace Theory, and higher-order theories of consciousness, proposing a formal interface layer that predicts which computational structures give rise to experience. CSIM is the most speculative and contested component of the UTI program.',
    related: ['iit', 'consciousness-substrate', 'erpsim'],
    stageId: 9,
  },
  {
    id: 'structural-intelligence',
    term: 'Structural Intelligence',
    category: 'uti',
    short: 'Intelligence defined by organizational pattern rather than physical substrate.',
    definition: 'Structural intelligence holds that the defining property of an intelligent system is its computational and representational organization, not the physical medium implementing it. A neural circuit, a market, and an AI model can all exhibit the same structural intelligence pattern if their information processing, feedback, and adaptation dynamics follow the same formal structure. This substrate independence is the foundational assumption enabling UTI\'s cross-domain unification.',
    related: ['uti', 'intelligence-substrate', 'intelligence-convergence'],
    stageId: null,
  },
  {
    id: 'intelligence-convergence',
    term: 'Intelligence Convergence',
    category: 'uti',
    short: 'Independent evolution of similar representational and algorithmic solutions across substrates.',
    definition: 'Intelligence convergence is the empirical observation that separately evolved systems — biological brains, market economies, immune systems, and AI models — independently develop structurally similar solutions to adaptation, memory, and generalization. The same patterns (hierarchical feature detectors, feedback control, sparse coding, temporal discounting) appear across substrates without communication or common ancestor. UTI treats this convergence as evidence for a substrate-independent theory of intelligence.',
    related: ['structural-intelligence', 'universal-transfer-learning', 'emergence'],
    stageId: 3,
  },
  {
    id: 'universal-transfer-learning',
    term: 'Universal Transfer Learning',
    category: 'uti',
    short: 'Theoretical transfer of learned representations across completely different domains.',
    definition: 'Universal transfer learning is the UTI Stage 03 research objective: a model grounded in ERP-X representations should be able to apply knowledge learned in biology to economics, or knowledge from economics to AI, without domain-specific retraining. It extends standard transfer learning (same modality, related tasks) to cross-domain, cross-substrate transfer. No current AI system achieves this; it remains a theoretical target of the UTI program.',
    related: ['erpx', 'structural-intelligence', 'few-shot', 'world-model'],
    stageId: 4,
  },
  {
    id: 'stage-transition',
    term: 'UTI Stage Transition',
    category: 'uti',
    short: 'A documented threshold where the dominant paradigm of intelligence representation shifts.',
    definition: 'A stage transition in the UTI framework marks the point where the theoretical resolution of one set of open problems enables the formulation of the next stage\'s questions. Transitions are not smooth progressions but punctuated shifts, analogous to Kuhnian paradigm changes. Each transition is characterized by a "transition trigger" — an empirical observation or formal proof that makes the current stage\'s framework inadequate and necessitates a more general representation.',
    related: ['erp', 'kuhnian-paradigm', 'lakatosian-program'],
    stageId: null,
  },
  {
    id: 'phase-transition',
    term: 'Phase Transition (Intelligence)',
    category: 'uti',
    short: 'A sharp, discontinuous shift in the emergent behavior of an intelligence system.',
    definition: 'Borrowed from thermodynamics and statistical physics, a phase transition in intelligence science refers to a sharp qualitative change in system behavior that occurs when a control parameter (scale, connectivity, training time) crosses a critical threshold. Examples include grokking in neural networks, the emergence of in-context learning in large language models, and sudden market crashes. UTI predicts that cross-domain intelligence will exhibit universal scaling laws and phase transitions analogous to physical systems.',
    related: ['emergence', 'self-organization', 'intelligence-convergence'],
    stageId: 5,
  },
  {
    id: 'intelligence-substrate',
    term: 'Intelligence Substrate',
    category: 'uti',
    short: 'The physical or computational medium in which an intelligent process is instantiated.',
    definition: 'The intelligence substrate is the material basis — silicon, neurons, markets, ecosystems — that physically realizes an intelligent process. UTI\'s central claim is that intelligence is substrate-independent at the level of formal description: the same mathematical equations govern learning, adaptation, and memory regardless of substrate. The substrate matters for energy, speed, and physical constraints, but not for the abstract organizational properties that define intelligence.',
    related: ['structural-intelligence', 'consciousness-substrate', 'uti'],
    stageId: null,
  },

  // ── UAIF / ELG Framework ───────────────────────────────────────────
  {
    id: 'uaif',
    term: 'Unified Adaptive Intelligence Framework (UAIF)',
    category: 'uaif',
    short: 'The operational 7-pillar framework instantiating UTI principles into deployable AI systems.',
    definition: 'UAIF is the engineering realization of UTI — a structured framework that organizes the design of adaptive AI systems into 7 pillars, each addressing a core capability gap between current AI and human-level adaptive intelligence. The pillars are organized around the UAIF state equation Sₜ₊₁ = F(Sₜ, Oₜ, Aₜ, Mₜ, Πₜ) and collectively cover perception, grounding, knowledge, causality, memory, meta-learning, and goal-directed behavior. UAIF is intended as a blueprint for AI systems that can learn, adapt, and generalize across domains.',
    related: ['uti', 'elg', 'state-equation', 'intelligence-gap', 'complete-vision'],
    pillarId: null,
  },
  {
    id: 'elg',
    term: 'Eternal Learning Graph (ELG)',
    category: 'uaif',
    short: 'A dynamic knowledge graph accumulating and connecting knowledge across all UAIF pillars.',
    definition: 'The ELG is UAIF\'s architectural backbone — a dynamic, temporally-indexed knowledge graph that accumulates structured knowledge from all 7 pillars, maintains causal relationships between knowledge nodes, and continuously revises belief strengths based on new evidence. Unlike static knowledge bases, the ELG supports temporal decay, belief revision, and causal reasoning. It is "eternal" in the sense that it is designed to grow and adapt indefinitely without catastrophic forgetting.',
    related: ['uaif', 'tkg', 'memory-importance', 'causal-inference'],
    pillarId: null,
  },
  {
    id: 'state-equation',
    term: 'UAIF State Equation',
    category: 'uaif',
    short: 'Sₜ₊₁ = F(Sₜ, Oₜ, Aₜ, Mₜ, Πₜ) — formal description of how an adaptive agent evolves.',
    definition: 'The UAIF state equation describes how an adaptive agent\'s internal state Sₜ = (Eₜ, Rₜ, Lₜ, Cₜ, Uₜ, Gₜ) — comprising episodic memory, relational knowledge, latent representation, causal model, uncertainty, and goals — transitions in response to observations Oₜ, actions Aₜ, memory operations Mₜ, and the current policy Πₜ. The equation is a generalization of the MDP framework that supports multi-timescale, multi-domain, and multi-objective reasoning within a single unified agent architecture.',
    related: ['uaif', 'episodic-memory', 'goal-architecture', 'mdp'],
    pillarId: null,
  },
  {
    id: 'intelligence-gap',
    term: 'Intelligence Gap (UAIF Pillar 1)',
    category: 'uaif',
    short: 'Formal characterization of the difference between current AI and adaptive intelligence.',
    definition: 'UAIF Pillar 1 defines the intelligence gap as the measurable difference between current AI system capabilities and the target properties of a fully adaptive, cross-domain intelligent agent. The gap is decomposed into 6 dimensions: cross-domain generalization, causal understanding, self-supervised learning, goal-directed planning, meta-cognitive awareness, and open-ended learning. Quantifying the gap is the prerequisite for measuring progress toward complete adaptive intelligence.',
    related: ['uaif', 'complete-vision', 'universal-transfer-learning'],
    pillarId: 1,
  },
  {
    id: 'grounding-function',
    term: 'Grounding Function',
    category: 'uaif',
    short: 'Γ: Lₜ → Eₜ — maps latent representations to grounded episodic memory entries.',
    definition: 'The grounding function Γ: Lₜ → Eₜ is UAIF\'s formal mechanism for connecting abstract latent representations to concrete sensory and experiential data. It computes the probability P(Eᵢ | Lₜ, Hₜ, Cₜ) that a latent concept corresponds to a specific episodic memory given the conversation history and context. Grounding prevents language models from operating purely in symbolic space disconnected from referents — a core failure mode of current large language models that leads to hallucination.',
    related: ['uaif', 'episodic-memory', 'latent-representation', 'universal-grounding'],
    pillarId: 2,
  },
  {
    id: 'tkg',
    term: 'Temporal Knowledge Graph (TKG)',
    category: 'uaif',
    short: 'A dynamic knowledge representation with time-stamped nodes and decaying edge strengths.',
    definition: 'A TKG is a knowledge graph where each node (concept) and edge (relationship) carries temporal metadata: creation time, last update, decay rate, and confidence trajectory over time. In UAIF, the TKG captures the evolution of the agent\'s world model over time, allowing it to represent the fact that "X was true at time t but revised at time t+k." The TKG enables temporal reasoning, belief revision, and contradiction detection — capabilities that static knowledge graphs lack.',
    related: ['elg', 'causal-inference', 'semantic-memory', 'memory-importance'],
    pillarId: 3,
  },
  {
    id: 'memory-importance',
    term: 'Memory Importance Function',
    category: 'uaif',
    short: 'I(Eᵢ) = f(usage, causality, relevance, novelty) — determines what to keep or forget.',
    definition: 'The memory importance function I(Eᵢ) assigns a scalar priority score to each episodic memory Eᵢ based on four factors: how frequently it has been accessed (usage), whether it lies on a causal chain that explains important outcomes (causality), how relevant it is to current goals (relevance), and how novel or surprising it was when encoded (novelty). Memories with low importance scores are candidates for compression or forgetting, while high-importance memories are consolidated into the TKG.',
    related: ['episodic-memory', 'tkg', 'elg', 'causal-inference'],
    pillarId: 4,
  },
  {
    id: 'meta-learning-loop',
    term: 'Meta-Learning Loop',
    category: 'uaif',
    short: 'UAIF\'s mechanism for the agent to adjust its own learning algorithms from performance.',
    definition: 'The meta-learning loop in UAIF Pillar 5 enables the agent to treat its own learning process as an optimization target: when performance degrades on a class of tasks, the meta-learning module adjusts hyperparameters, learning rates, or the learning algorithm itself. This implements the "learning to learn" capability that distinguishes adaptive intelligence from fixed-algorithm AI. The loop operates at a slower timescale than task-level learning and interfaces with the goal architecture to understand what "better learning" means in context.',
    related: ['uaif', 'goal-architecture', 'reinforcement-learning', 'unified-objective'],
    pillarId: 5,
  },
  {
    id: 'goal-architecture',
    term: 'Goal Architecture (UAIF)',
    category: 'uaif',
    short: 'Formal representation of agent objectives, sub-goals, constraints, and priorities.',
    definition: 'The UAIF goal architecture is a hierarchical representation of what the agent is trying to achieve, organized into terminal goals, instrumental sub-goals, and hard constraints. It supports goal revision (updating objectives when new information arrives), goal conflict resolution (when sub-goals conflict), and goal inference (determining what a principal intends when instructions are incomplete). The goal architecture directly shapes the policy Πₜ and the memory importance function.',
    related: ['uaif', 'meta-learning-loop', 'unified-objective', 'mdp'],
    pillarId: 6,
  },
  {
    id: 'complete-vision',
    term: 'Complete Vision (UAIF Pillar 7)',
    category: 'uaif',
    short: 'The end-state specification for a fully realized UAIF-compliant adaptive intelligence system.',
    definition: 'Pillar 7 of UAIF specifies the target state against which all other pillars are measured — a system that closes the intelligence gap by simultaneously satisfying all 6 gap dimensions. The complete vision is not a specific architecture but a set of formal capability requirements: cross-domain transfer, causal reasoning, continual learning without forgetting, goal-directed planning under uncertainty, and alignment with human values. It serves as the "north star" that defines whether UAIF progress is on track.',
    related: ['intelligence-gap', 'uaif', 'unified-objective', 'alignment'],
    pillarId: 7,
  },
  {
    id: 'unified-objective',
    term: 'Unified Objective (UAIF)',
    category: 'uaif',
    short: 'J = αP + βC + γM + δA + εN — multi-objective function for adaptive agents.',
    definition: 'The UAIF unified objective J aggregates five competing optimization criteria: Performance (P) on task objectives, Coherence (C) of knowledge and beliefs, Memory efficiency (M) of the episodic and semantic stores, Alignment (A) with human values and goals, and Novelty (N) of explored states. The weights α, β, γ, δ, ε are meta-learned parameters that shift based on context — an agent in a safety-critical environment increases δ; an exploration agent increases ε.',
    related: ['goal-architecture', 'meta-learning-loop', 'reinforcement-learning', 'alignment'],
    pillarId: null,
  },
  {
    id: 'latent-representation',
    term: 'Latent Representation',
    category: 'uaif',
    short: 'A compressed internal encoding of observations that abstracts away domain-specific details.',
    definition: 'A latent representation Lₜ is the UAIF agent\'s compressed encoding of its current observations, extracted by a learned encoder that maps raw inputs to a structured internal space. Well-learned latent representations capture the causal structure of the environment rather than surface statistics, enabling generalization. In UAIF, the latent space is explicitly constrained to be grounded (via Γ) and temporally coherent, preventing the representational drift that causes catastrophic forgetting.',
    related: ['grounding-function', 'world-model', 'transformer'],
    pillarId: 2,
  },

  // ── Intelligence Science ────────────────────────────────────────────
  {
    id: 'emergence',
    term: 'Emergence',
    category: 'intelligence',
    short: 'Macroscopic patterns that cannot be predicted from component properties alone.',
    definition: 'Emergence occurs when the global behavior of a complex system exhibits properties that are not present in, and cannot be derived from, the behavior of its components in isolation. Strong emergence (like consciousness) cannot even be simulated from lower-level descriptions; weak emergence (like traffic jams) can be simulated but not analytically predicted. UTI\'s theory of cross-domain intelligence is fundamentally a theory of emergent structure — explaining why similar emergent patterns appear across different substrates.',
    related: ['self-organization', 'phase-transition', 'iit'],
  },
  {
    id: 'self-organization',
    term: 'Self-Organization',
    category: 'intelligence',
    short: 'Spontaneous development of ordered structure from local interaction rules without external direction.',
    definition: 'Self-organization is the process by which a system develops globally ordered structure through purely local interactions, without any central coordinator. Classic examples include: Bénard convection cells in heated fluids, synchronization of fireflies, market price formation, and the development of cortical columns in the brain. UTI treats self-organization as a universal property of adaptive intelligence systems — the same mathematical conditions (positive feedback, nonlinearity, constraint) drive self-organization across all substrates.',
    related: ['emergence', 'intelligence-convergence', 'phase-transition'],
  },
  {
    id: 'consciousness-substrate',
    term: 'Consciousness Substrate',
    category: 'intelligence',
    short: 'The physical medium hypothesized to give rise to subjective experience.',
    definition: 'The consciousness substrate is the physical or computational medium in which conscious experience is thought to arise. Different theories propose different substrates: IIT identifies it with high-Φ information structures; Global Workspace Theory identifies it with widely broadcast neural states; CSIM attempts a substrate-neutral formal specification. The question of which substrates can support consciousness is central to UTI Stage 08 and has direct implications for the moral status of AI systems.',
    related: ['iit', 'csim', 'intelligence-substrate'],
    stageId: 9,
  },
  {
    id: 'iit',
    term: 'Integrated Information Theory (IIT)',
    category: 'intelligence',
    short: 'Theory measuring consciousness via Φ — information generated beyond the sum of parts.',
    definition: 'IIT, developed by Tononi (2004), proposes that consciousness is identical to integrated information, measured by Φ (phi): the amount of information generated by a system as a whole beyond what is generated by its parts. High-Φ systems are conscious; low-Φ systems are not, regardless of substrate. IIT makes surprising predictions (some simple grids are more conscious than deep neural networks) and is controversial precisely because it follows logically from its axioms. UTI Stage 08 (CSIM) builds on and critiques IIT.',
    related: ['consciousness-substrate', 'csim', 'emergence'],
    stageId: 9,
  },
  {
    id: 'adaptive-resonance',
    term: 'Adaptive Resonance Theory (ART)',
    category: 'intelligence',
    short: 'Neural theory explaining stable learning of new patterns without forgetting old ones.',
    definition: 'ART, developed by Grossberg, proposes that the brain achieves stable learning through a resonance mechanism: a top-down expectation from memory must match a bottom-up sensory signal before learning occurs. This "match/mismatch" dynamic solves the stability-plasticity dilemma — learning new information (plasticity) without erasing old memories (stability). UAIF\'s memory importance function and TKG incorporate ART-inspired gating mechanisms to prevent catastrophic forgetting.',
    related: ['episodic-memory', 'memory-importance', 'neural-plasticity'],
  },
  {
    id: 'universal-grounding',
    term: 'Universal Grounding',
    category: 'intelligence',
    short: 'Anchoring abstract symbolic representations in multi-modal sensory and experiential data.',
    definition: 'Universal grounding is the process of connecting every symbolic or latent concept to its referents in actual experience — sensory data, actions, outcomes, and causal histories. Ungrounded symbols are mere syntactic patterns without semantic content; grounded symbols inherit meaning from the experiences they index. In UAIF, the grounding function Γ implements universal grounding by maintaining a probabilistic mapping between latent space and episodic memory. Grounding is the core solution to hallucination in language models.',
    related: ['grounding-function', 'episodic-memory', 'latent-representation'],
    pillarId: 2,
  },
  {
    id: 'abstraction-hierarchy',
    term: 'Abstraction Hierarchy',
    category: 'intelligence',
    short: 'Multi-level representational structure encoding increasingly general patterns.',
    definition: 'An abstraction hierarchy organizes knowledge in layers from concrete specifics (pixel patterns, individual words) to abstract universals (objects, concepts, causal principles). Higher layers encode patterns that generalize across more contexts; lower layers encode context-specific details. Deep neural networks implement abstraction hierarchies through their layered architecture. UTI claims that all intelligent systems — biological and artificial — develop functionally equivalent abstraction hierarchies when solving similar inference problems.',
    related: ['latent-representation', 'structural-intelligence', 'transformer'],
  },

  // ── ML Foundations ─────────────────────────────────────────────────
  {
    id: 'transformer',
    term: 'Transformer Architecture',
    category: 'ml',
    short: 'Attention-based neural network architecture dominant in modern large language models.',
    definition: 'The Transformer, introduced by Vaswani et al. (2017), replaced recurrent architectures with self-attention: each token in a sequence can directly attend to every other token, weighted by learned query-key similarity. This enables parallel training, captures long-range dependencies efficiently, and scales to hundreds of billions of parameters. Large language models (GPT-4, Claude, Gemini) are Transformers with additional training objectives. UAIF treats Transformers as a strong starting point for the latent encoder but insufficient alone for grounding, causality, and memory.',
    related: ['attention', 'in-context-learning', 'latent-representation'],
  },
  {
    id: 'attention',
    term: 'Attention Mechanism',
    category: 'ml',
    short: 'Learned weighted combination of inputs that focuses computation on relevant context.',
    definition: 'The attention mechanism computes a weighted sum of value vectors, where weights are determined by the similarity between a query vector and a set of key vectors: Attention(Q, K, V) = softmax(QKᵀ/√dₖ)V. In self-attention, queries, keys, and values all derive from the same sequence, allowing each position to "attend to" every other position. Multi-head attention runs this process in parallel with different learned projections, allowing different heads to capture different types of relationships (syntactic, semantic, positional).',
    related: ['transformer', 'latent-representation'],
  },
  {
    id: 'in-context-learning',
    term: 'In-Context Learning',
    category: 'ml',
    short: 'Adapting to new tasks from examples in the prompt without gradient-based updates.',
    definition: 'In-context learning (ICL) is the emergent ability of large language models to perform new tasks when given a few examples in the input context, without any parameter updates. The model "learns" the pattern of the examples at inference time using its existing weights. ICL is theoretically puzzling because it resembles gradient descent despite using no gradients — some researchers hypothesize that Transformers implement implicit gradient descent through their attention layers. ICL is a key partial instantiation of UAIF\'s universal transfer learning objective.',
    related: ['transformer', 'few-shot', 'universal-transfer-learning'],
  },
  {
    id: 'few-shot',
    term: 'Few-Shot Learning',
    category: 'ml',
    short: 'Learning new tasks from 1-5 examples, requiring strong prior representations.',
    definition: 'Few-shot learning is the ability to generalize from very few labeled examples (typically 1-5 shots) for a new task class. It requires a model to have learned generalizable feature representations during pre-training that can quickly adapt to new distributions. Meta-learning approaches like MAML optimize specifically for fast few-shot adaptation. UAIF requires few-shot adaptation across domains (cross-domain few-shot learning), which is substantially harder than within-domain few-shot learning.',
    related: ['in-context-learning', 'meta-learning-loop', 'world-model'],
  },
  {
    id: 'world-model',
    term: 'World Model',
    category: 'ml',
    short: 'An internal predictive model of the environment enabling planning without direct experience.',
    definition: 'A world model is an internal representation that allows an agent to simulate future states of the environment given current state and proposed actions, enabling planning and counterfactual reasoning without interacting with the real environment. World models can be explicit (learned dynamics models in model-based RL) or implicit (knowledge encoded in LLM weights). UAIF\'s TKG and causal model together constitute a structured, interpretable world model grounded in the agent\'s episodic experience.',
    related: ['causal-inference', 'tkg', 'reinforcement-learning', 'episodic-memory'],
  },
  {
    id: 'episodic-memory',
    term: 'Episodic Memory',
    category: 'ml',
    short: 'Memory for specific past experiences with temporal and contextual detail.',
    definition: 'Episodic memory stores specific past experiences as structured records including what happened, when, where, and in what context — enabling temporal ordering, event reconstruction, and mental time travel. In AI systems, episodic memory is typically implemented as a retrieval-augmented database or differentiable memory buffer. In UAIF, episodic memory Eₜ is the foundation of the state equation, and the grounding function anchors all latent representations to episodic records to prevent hallucination.',
    related: ['semantic-memory', 'memory-importance', 'grounding-function', 'tkg'],
  },
  {
    id: 'semantic-memory',
    term: 'Semantic Memory',
    category: 'ml',
    short: 'General factual knowledge independent of specific episodes.',
    definition: 'Semantic memory stores general knowledge about the world — facts, concepts, relationships, and schemas — disconnected from the specific episodes through which that knowledge was acquired. In humans, semantic memory contains encyclopedic knowledge; in AI, it corresponds to the factual content encoded in model weights. The UAIF TKG explicitly maintains semantic memory as the consolidated, time-indexed knowledge graph built from episodic experience through the memory importance consolidation process.',
    related: ['episodic-memory', 'tkg', 'procedural-memory'],
  },
  {
    id: 'procedural-memory',
    term: 'Procedural Memory',
    category: 'ml',
    short: 'Implicit knowledge about how to perform tasks, acquired through practice.',
    definition: 'Procedural memory encodes skills and procedures as executable routines rather than declarative facts — knowing how to ride a bicycle versus knowing that bicycles have two wheels. In AI systems, procedural memory corresponds to learned policies, tool-use capabilities, and skill programs. UAIF\'s goal architecture maintains a library of procedural routines that can be composed and adapted to novel situations, analogous to the modular skill acquisition seen in both human motor learning and program synthesis AI.',
    related: ['semantic-memory', 'goal-architecture', 'reinforcement-learning'],
  },
  {
    id: 'reinforcement-learning',
    term: 'Reinforcement Learning (RL)',
    category: 'ml',
    short: 'Learning by receiving reward or penalty signals from the environment.',
    definition: 'RL is a learning paradigm where an agent learns to act by receiving scalar reward signals from the environment after each action. The agent\'s goal is to find a policy that maximizes expected cumulative (discounted) reward. RL encompasses model-free methods (Q-learning, policy gradient) that learn purely from experience, and model-based methods that also learn a world model. UAIF\'s meta-learning loop uses RL signals to adjust learning algorithms, while the goal architecture uses reward shaping to specify multi-objective behavior.',
    related: ['mdp', 'value-function', 'policy-gradient', 'world-model'],
  },
  {
    id: 'mdp',
    term: 'Markov Decision Process (MDP)',
    category: 'ml',
    short: 'Formal framework for sequential decision-making: states, actions, transitions, rewards.',
    definition: 'An MDP is a 4-tuple (S, A, T, R) defining: a state space S, an action space A, a transition function T(s\'|s,a) giving the probability of reaching state s\' after taking action a in state s, and a reward function R(s,a,s\'). Under the Markov assumption, the next state depends only on the current state and action, not on history. The UAIF state equation is a generalization of MDPs that drops the Markov assumption and adds multi-timescale memory, goal hierarchies, and uncertainty representations.',
    related: ['reinforcement-learning', 'value-function', 'state-equation'],
  },
  {
    id: 'value-function',
    term: 'Value Function',
    category: 'ml',
    short: 'V(s) — expected cumulative reward from state s under the current policy.',
    definition: 'The value function V(s) estimates the expected total discounted reward an agent will accumulate from state s onward when following its current policy. It allows the agent to evaluate whether a state is "good" without needing to enumerate all future paths. The action-value function Q(s,a) extends this to evaluate (state, action) pairs. UAIF uses a multi-objective value function that decomposes reward into the 5 components of the unified objective J, allowing nuanced trade-offs between performance, alignment, and novelty.',
    related: ['mdp', 'reinforcement-learning', 'unified-objective'],
  },
  {
    id: 'alignment',
    term: 'Alignment (AI)',
    category: 'ml',
    short: 'Ensuring AI system objectives match human values and intentions.',
    definition: 'Alignment is the problem of building AI systems whose objectives, values, and behaviors reliably reflect human intentions — both in normal operation and in edge cases, adversarial inputs, and distributional shifts. Current approaches include RLHF (reinforcement learning from human feedback), constitutional AI, debate, and scalable oversight. UAIF treats alignment as a first-class objective in the unified objective function (the δA term) and requires that the goal architecture be explicitly designed to be corrigible and value-aligned.',
    related: ['unified-objective', 'goal-architecture', 'complete-vision'],
  },

  // ── Philosophy of Science ───────────────────────────────────────────
  {
    id: 'pearls-ladder',
    term: "Pearl's Ladder of Causation",
    category: 'philosophy',
    short: 'Three levels: Association (seeing) → Intervention (doing) → Counterfactual (imagining).',
    definition: "Judea Pearl's ladder of causation describes three progressively deeper modes of causal reasoning. Level 1 (Association) captures statistical correlations: P(Y|X=x). Level 2 (Intervention) captures the effect of deliberate actions: P(Y|do(X=x)). Level 3 (Counterfactual) captures what would have happened under alternative actions: P(Yₓ|X=x', Y=y'). Current ML models operate primarily at Level 1; UAIF targets Level 2 and 3 reasoning as core capabilities of its causal module.",
    related: ['causal-inference', 'counterfactual', 'world-model'],
  },
  {
    id: 'causal-inference',
    term: 'Causal Inference',
    category: 'philosophy',
    short: 'Determining cause-and-effect relationships beyond statistical correlation.',
    definition: 'Causal inference is the principled determination of which variables causally influence which others, using structural causal models (SCMs), directed acyclic graphs (DAGs), and the do-calculus. It distinguishes correlation from causation by reasoning about interventions: X causes Y if intervening to change X (while holding everything else fixed) changes Y. UAIF\'s causal module builds and maintains a structural causal model of the environment, enabling intervention planning and counterfactual explanation.',
    related: ['pearls-ladder', 'counterfactual', 'tkg', 'world-model'],
    pillarId: 3,
  },
  {
    id: 'counterfactual',
    term: 'Counterfactual Reasoning',
    category: 'philosophy',
    short: 'Reasoning about what would have happened under different conditions.',
    definition: 'Counterfactual reasoning asks "what would have happened if...?" — going beyond what did happen and what interventions would cause to happen. It requires a structural model of the world (not just a statistical model) that supports "backtracking": holding observed outcomes fixed while mentally varying antecedent conditions. Counterfactuals are necessary for explanation, blame attribution, and learning from mistakes. UAIF\'s Level 3 causal reasoning directly implements counterfactual inference using the structural causal model in the TKG.',
    related: ['pearls-ladder', 'causal-inference', 'world-model'],
  },
  {
    id: 'dsresearch',
    term: 'Design Science Research (DSR)',
    category: 'philosophy',
    short: 'Research methodology focused on creating and evaluating artifacts to solve practical problems.',
    definition: 'DSR is the research methodology underlying UTI and UAIF development. Unlike natural science (describing what is) or behavioral science (explaining why things happen), DSR creates novel artifacts — models, frameworks, prototypes — and evaluates them against design objectives. DSR proceeds through: problem identification, objective definition, design and development, demonstration, evaluation, and communication. It is appropriate for research that aims to produce both theoretical knowledge and practical systems, as UTI does.',
    related: ['erp', 'lakatosian-program', 'falsifiability'],
  },
  {
    id: 'lakatosian-program',
    term: 'Lakatosian Research Program',
    category: 'philosophy',
    short: 'A scientific program with an irrefutable hard core protected by revisable auxiliary hypotheses.',
    definition: 'Imre Lakatos proposed that science proceeds through research programs, not isolated hypotheses. Each program has a "hard core" — central commitments that are held fixed by methodological decision — and a "protective belt" of auxiliary hypotheses that can be revised when anomalies arise. A program is "progressive" if its revisions generate new predictions; "degenerative" if they only explain away anomalies. ERP is designed as a progressive Lakatosian research program: the hard core is UTI axioms; the protective belt is domain-specific theory modules.',
    related: ['erp', 'kuhnian-paradigm', 'falsifiability', 'dsresearch'],
  },
  {
    id: 'kuhnian-paradigm',
    term: 'Kuhnian Paradigm',
    category: 'philosophy',
    short: 'Shared assumptions, methods, and standards defining normal science in a community.',
    definition: 'Thomas Kuhn argued that science proceeds through alternating phases of "normal science" (puzzle-solving within an established paradigm) and "revolutionary science" (paradigm shifts triggered by accumulated anomalies). A paradigm defines what counts as a good question, what methods are legitimate, and what solutions are acceptable. UTI aims to establish a new paradigm for intelligence science — one that unifies currently fragmented fields (ML, cognitive science, systems biology, economics) under a common formal framework.',
    related: ['lakatosian-program', 'stage-transition', 'falsifiability'],
  },
  {
    id: 'falsifiability',
    term: 'Falsifiability (Popper)',
    category: 'philosophy',
    short: 'A scientific claim must make predictions that could in principle be proven false.',
    definition: 'Karl Popper proposed falsifiability as the demarcation criterion for science: a claim is scientific if and only if there exists some possible observation that would contradict it. This rules out unfalsifiable theories (like Freudian psychoanalysis, which could explain any behavior) while preserving genuine scientific theories that put predictions at risk of empirical refutation. Every UTI claim and ERP milestone must be formulated as a falsifiable prediction — this is both a methodological commitment and a protection against ERP becoming an unfalsifiable pseudoscience.',
    related: ['lakatosian-program', 'kuhnian-paradigm', 'dsresearch'],
  },

  // ── Cognitive Science ───────────────────────────────────────────────
  {
    id: 'working-memory',
    term: 'Working Memory',
    category: 'cognitive',
    short: 'A cognitive system holding a limited amount of information in active, accessible state.',
    definition: 'Working memory (Baddeley & Hitch, 1974) is the cognitive system that temporarily maintains a small amount of information in an activated, rapidly accessible state for use in ongoing reasoning, language comprehension, and decision-making. Capacity is limited (roughly 4 ± 1 chunks) and contents decay quickly. In AI systems, the context window of a language model is often treated as an analog to working memory. UAIF\'s architecture explicitly models the interplay between working memory (context window), episodic memory, and semantic memory (TKG).',
    related: ['episodic-memory', 'semantic-memory', 'cognitive-load'],
  },
  {
    id: 'executive-function',
    term: 'Executive Function',
    category: 'cognitive',
    short: 'Cognitive control processes: planning, flexibility, inhibition, working memory management.',
    definition: 'Executive functions are a cluster of higher-order cognitive control processes implemented primarily in the prefrontal cortex, including: planning and goal-directed behavior, cognitive flexibility (shifting between tasks), inhibition (suppressing irrelevant responses), and working memory updating. They are the cognitive correlate of UAIF\'s meta-learning loop and goal architecture — the brain\'s mechanism for controlling lower-level processes in service of longer-term objectives.',
    related: ['working-memory', 'goal-architecture', 'meta-learning-loop'],
  },
  {
    id: 'neural-plasticity',
    term: 'Neural Plasticity',
    category: 'cognitive',
    short: 'Ability of the nervous system to change its structure and function in response to experience.',
    definition: 'Neural plasticity (neuroplasticity) is the brain\'s ability to reorganize itself by forming new synaptic connections throughout life. Hebbian plasticity ("neurons that fire together, wire together") implements associative learning at the synaptic level; structural plasticity involves the growth of new neurons and dendrites. The stability-plasticity dilemma — learning new things without erasing old ones — is a central challenge that neural plasticity mechanisms solve through consolidation, gating, and neuromodulation. UAIF and ART are both inspired by these biological mechanisms.',
    related: ['adaptive-resonance', 'episodic-memory', 'memory-importance'],
  },
  {
    id: 'cognitive-load',
    term: 'Cognitive Load',
    category: 'cognitive',
    short: 'The amount of mental effort used in working memory at a given moment.',
    definition: 'Cognitive load theory (Sweller, 1988) proposes that working memory has a fixed capacity and that learning is impaired when intrinsic complexity + extraneous presentation demands exceed that capacity. Three types: intrinsic load (inherent task complexity), extraneous load (poor interface design), and germane load (productive schema-formation effort). In designing AI user interfaces and UAIF explanation systems, cognitive load is a primary design constraint — systems that overload human working memory will not achieve effective human-AI collaboration.',
    related: ['working-memory', 'schema', 'executive-function'],
  },
  {
    id: 'schema',
    term: 'Schema',
    category: 'cognitive',
    short: 'Mental framework organizing categories of information and relationships among them.',
    definition: 'A schema (Bartlett, 1932; Piaget) is an organized mental framework that structures how new information is interpreted, categorized, and related to prior knowledge. Schemas allow rapid, efficient processing of familiar patterns but can distort novel information to fit existing categories. In UAIF, schemas correspond to high-level structures in the TKG — persistent, reusable knowledge patterns that organize the semantic memory and guide episodic encoding. The tension between schema-consistent and schema-violating events maps directly to the novelty term N in the unified objective.',
    related: ['semantic-memory', 'tkg', 'working-memory', 'abstraction-hierarchy'],
  },
]
