// Problem Space — data for /problem-space page

export const visionStatement = {
  headline: 'What Is This Research Trying to Solve?',
  coreProblem:
    'Despite decades of progress, AI systems remain brittle, opaque, and incapable of general reasoning. ' +
    'They excel at pattern matching within narrow distribution but fail when context shifts, when causal reasoning is required, ' +
    'or when the goal demands integrating knowledge across domains. Meanwhile, intelligence science has no agreed formal theory — ' +
    'biology, cognitive science, and AI each maintain their own incompatible vocabularies and assumptions.',
  motivation:
    'The UTI/UAIF research program exists to close this gap by building a substrate-independent, mathematically rigorous theory of ' +
    'intelligence that (1) unifies descriptions across biological and artificial systems, (2) identifies the structural invariants that ' +
    'all intelligent systems share, and (3) translates those invariants into an engineering blueprint for adaptive AI.',
  aspirations: [
    { icon: '🔭', label: 'Unified Theory', text: 'A single formal framework that describes intelligence regardless of substrate — neurons, silicon, markets, ecosystems.' },
    { icon: '⚙️', label: 'Engineering Blueprint', text: 'UAIF: a 7-pillar architecture derived from UTI that specifies how to build genuinely adaptive AI systems.' },
    { icon: '♾️', label: 'Eternal Program', text: 'A self-sustaining Eternal Research Program (ERP) governed by formal protocols that outlives any individual researcher.' },
    { icon: '🔬', label: 'Falsifiable Claims', text: 'Every stage of UTI produces testable predictions and design artifacts that can be empirically evaluated and rejected.' },
  ],
}

// ─── Research Questions ────────────────────────────────────────────────────────
export const researchQuestions = [
  {
    id: 'RQ1',
    question: 'Can intelligence be formally defined in a substrate-independent manner?',
    category: 'theoretical',
    status: 'partial',
    relatedStages: [1, 2, 3],
    hypothesis:
      'Intelligence is a property of information-processing systems that maintain and update compact state representations to optimize multi-objective goals across varying environments. This definition applies equally to neural, silicon, organizational, and ecological substrates.',
    subQuestions: [
      'What mathematical structure best captures the representational capacity required for intelligence?',
      'Does the definition need to be constructive (algorithmic) or axiomatic (formal)?',
      'How does the definition handle degenerate cases — simple reflexes, optimization algorithms, social institutions?',
    ],
    whyItMatters: 'Without a formal definition, we cannot measure intelligence, compare systems, or build theories that make predictions. Every field currently uses its own informal notion.',
  },
  {
    id: 'RQ2',
    question: 'What mathematical structures best capture the convergent properties of intelligent systems?',
    category: 'theoretical',
    status: 'partial',
    relatedStages: [2, 3, 4],
    hypothesis:
      'State-space equations, attractor dynamics, and causal DAGs together form a sufficient mathematical vocabulary for describing structural intelligence — capturing stability, phase transitions, and goal-directedness in a unified formalism.',
    subQuestions: [
      'Is category theory a better foundation than set theory for cross-substrate comparison?',
      'How are attractor landscapes in neural systems analogous to search landscapes in optimization?',
      'Can topological invariants capture the "shape" of an intelligence system\'s representational space?',
    ],
    whyItMatters: 'Mathematics is the only language precise enough to support falsifiable cross-substrate comparisons. Without it, "intelligence is like evolution" remains metaphor, not science.',
  },
  {
    id: 'RQ3',
    question: 'How can symbolic knowledge be grounded in sensorimotor experience without losing compositional expressiveness?',
    category: 'design',
    status: 'open',
    relatedStages: [5, 6],
    hypothesis:
      'A learned grounding function mapping high-dimensional perceptual inputs to a structured latent space, trained jointly with a symbolic inference engine, can preserve both the compositionality of language and the referential anchoring of embodied perception.',
    subQuestions: [
      'What loss functions enforce grounding during joint training?',
      'Can grounding generalize zero-shot to novel concept combinations?',
      'How does grounding degrade under distribution shift and how can it be repaired?',
    ],
    whyItMatters: 'The symbol grounding problem is the central obstacle to moving AI beyond pattern matching to genuine understanding. Without grounding, language models manipulate syntax without semantics.',
  },
  {
    id: 'RQ4',
    question: 'What minimal architectural requirements must an AI system satisfy to exhibit genuine adaptive intelligence?',
    category: 'design',
    status: 'partial',
    relatedStages: [6, 7, 8],
    hypothesis:
      'Genuine adaptive intelligence requires: (1) a grounded latent state space, (2) a temporal knowledge graph for structured episodic memory, (3) a causal world model, (4) meta-learning over its own weight manifold, and (5) a multi-objective goal architecture with conflict resolution. These five components correspond to UAIF Pillars 1–5.',
    subQuestions: [
      'Are all five components necessary or can some be substituted?',
      'What is the minimal parameterization of each component that still exhibits adaptive behavior?',
      'How do the components interact — are there phase transitions in capability as components are combined?',
    ],
    whyItMatters: 'Current AI architectures lack a principled theory of which components matter. This leads to heuristic engineering. A principled minimum enables systematic design.',
  },
  {
    id: 'RQ5',
    question: 'How does intelligence transfer structurally across radically different domains?',
    category: 'empirical',
    status: 'open',
    relatedStages: [3, 7, 9],
    hypothesis:
      'Cross-domain transfer succeeds when systems share structural invariants (attractor topology, causal graph shape, goal hierarchy depth) even when surface features differ completely. Transfer fails when structural invariants diverge.',
    subQuestions: [
      'Can we measure structural similarity between domains without a shared ontology?',
      'What training interventions maximize structural rather than surface learning?',
      'How does transfer interact with grounding — does a grounded system transfer better?',
    ],
    whyItMatters: 'Transfer learning is the key bottleneck in AI generalization. Current approaches treat it as a statistical problem; UTI predicts it is a structural problem with a principled solution.',
  },
  {
    id: 'RQ6',
    question: 'Under what conditions can an intelligent system stably improve its own architecture without entering recursive instability?',
    category: 'theoretical',
    status: 'open',
    relatedStages: [8, 9],
    hypothesis:
      'Stable self-modification requires a fixed formal objective function and a constrained meta-learning operator that cannot modify the objective itself. Self-improvement is provably stable when it is bounded by the curvature of the loss landscape at the current architecture.',
    subQuestions: [
      'What formal conditions on the meta-learning operator guarantee convergence?',
      'Can an agent verify its own stability without an external oracle?',
      'How do formal constraints interact with open-ended environments?',
    ],
    whyItMatters: 'Self-improvement is the gateway to Stage 09 of UTI — the Eternal Research Program. Without a stability theory, autonomous research programs are unsafe.',
  },
  {
    id: 'RQ7',
    question: 'What institutional and governance structures are necessary for a research program to be self-sustaining across generations?',
    category: 'design',
    status: 'open',
    relatedStages: [9, 10],
    hypothesis:
      'An Eternal Research Program requires: a formal protocol for knowledge accumulation, a governance structure with succession rules, a benchmark infrastructure for measuring progress, and an incentive system that rewards long-horizon contributions over short-term publication metrics.',
    subQuestions: [
      'What formal protocol ensures knowledge is cumulative rather than fragmented?',
      'How do ERP governance rules handle paradigm shifts that invalidate prior work?',
      'What is the minimum viable institution for an ERP in the current academic landscape?',
    ],
    whyItMatters: 'Stage 10 of UTI is the ERP itself. Without a theory of how to sustain a research program, the framework cannot achieve its own goal.',
  },
  {
    id: 'RQ8',
    question: 'Is the 10-stage UTI progression empirically falsifiable, and if so, what experiments would refute it?',
    category: 'empirical',
    status: 'partial',
    relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    hypothesis:
      'UTI is falsifiable at two levels: (1) each stage makes structural predictions about the capabilities of systems at that stage, and (2) the ordering of stages predicts that later capabilities cannot emerge without earlier ones. Falsification would require an empirical demonstration of a system exhibiting Stage N+1 capabilities without Stage N properties.',
    subQuestions: [
      'What are the minimal capability benchmarks for each stage?',
      'Can a system exhibit capability indicators from multiple stages simultaneously, and what does that imply?',
      'How do we handle systems that appear to skip stages (e.g., LLMs exhibiting Stage 6 behaviors without Stage 3)?',
    ],
    whyItMatters: 'Scientific validity requires falsifiability. Without a clear falsification protocol, UTI risks being unfalsifiable metaphysics rather than science.',
  },
]

// ─── Primitive Questions ───────────────────────────────────────────────────────
export const primitiveQuestions = [
  {
    id: 'PQ1',
    question: 'Can formal systems capture meaning, or is meaning always extra-formal?',
    domain: 'philosophy',
    currentConsensus: 'Deeply contested. Gödel incompleteness, Chinese Room argument, and the semantics-syntax gap all suggest formal systems cannot self-ground. Functionalists argue meaning supervenes on causal/functional structure.',
    tension: 'If formal systems cannot capture meaning, UTI\'s mathematical formalization is inherently incomplete. If they can, the symbol grounding problem dissolves — but no one has demonstrated how.',
    whyItMatters: 'This question determines whether a mathematical theory of intelligence is even possible in principle.',
    positions: ['Formalism (Frege, Russell): meaning is formal structure', 'Phenomenology (Husserl, Merleau-Ponty): meaning requires embodied experience', 'Functionalism (Putnam, Dennett): meaning is functional role', 'Wittgenstein: meaning is use in language games'],
  },
  {
    id: 'PQ2',
    question: 'Is consciousness necessary for general intelligence?',
    domain: 'philosophy',
    currentConsensus: 'No scientific consensus. Philosophical zombies thought experiment suggests they are separable. Integrated Information Theory (IIT) and Global Workspace Theory (GWT) tie consciousness to specific computational architectures.',
    tension: 'UTI aims to be substrate-independent and does not posit consciousness as necessary. But if consciousness enables forms of integration that unconscious computation cannot, the theory may have a hidden gap at Stage 8+.',
    whyItMatters: 'Determines whether UAIF can achieve Stage 9 behaviors (autonomous research) without requiring phenomenal consciousness.',
    positions: ['Higher-order theories: consciousness is meta-cognition', 'IIT: consciousness is integrated information above threshold', 'Functionalism: any sufficient functional organization is conscious', 'Eliminativism: consciousness is a folk-psychological category to be dissolved'],
  },
  {
    id: 'PQ3',
    question: 'What is the relationship between structural similarity and ontological identity across substrates?',
    domain: 'metaphysics',
    currentConsensus: 'Structural realism (Ladyman, French) holds that structural relations are all that exist — identity is defined by shared structure. Multiple realizability (Putnam) holds that the same function can be realized by different physical substrates.',
    tension: 'UTI\'s substrate-independence claim rests on the assumption that structural similarity is sufficient for theoretical unification. But if substrate matters for causal power (physical causal exclusion), the unification may be nominal rather than real.',
    whyItMatters: 'Determines whether UTI is a theory about a real unified phenomenon or a family of analogies.',
    positions: ['Structural realism: relations are ontologically primary', 'Multiple realizability: functional identity across substrates', 'Causal exclusion: higher-level causal descriptions are derivative', 'Process ontology (Whitehead): becoming is more fundamental than structure'],
  },
  {
    id: 'PQ4',
    question: 'Is causation fundamental or derived from probabilistic correlation?',
    domain: 'philosophy of science',
    currentConsensus: 'Pearl\'s causal hierarchy distinguishes association, intervention, and counterfactual levels. Most AI systems operate at Level 1 (association). Whether causation is fundamental or reducible to interventionist counterfactuals is contested.',
    tension: 'UAIF Pillar 4 (Causal Reasoning) requires a formal causal module. If causation is not fundamental but derived, the causal module is an approximation — a useful engineering fiction rather than a principled mechanism.',
    whyItMatters: 'Determines the theoretical grounding and expected generalization limits of the causal module in UAIF.',
    positions: ['Regularity theory (Hume): causation is constant conjunction', 'Interventionist theory (Pearl, Woodward): causation is intervention-invariant', 'Dispositional theory: causation involves real powers/dispositions', 'Eliminativist: causation is a cognitive projection'],
  },
  {
    id: 'PQ5',
    question: 'What distinguishes knowledge from information from data?',
    domain: 'epistemology',
    currentConsensus: 'The DIKW hierarchy (Data→Information→Knowledge→Wisdom) is widely used but poorly defined. Propositional knowledge requires justification (JTB); procedural knowledge is know-how. Floridi\'s semantic theory of information ties information to meaning.',
    tension: 'UTI\'s Temporal Knowledge Graph is claimed to store "knowledge" — but if knowledge requires justification and TKGs store only propositional content indexed by time, the claim may be imprecise. The theory needs a precise knowledge epistemology.',
    whyItMatters: 'The distinction matters for designing memory architectures and evaluating whether an AI system "knows" vs. "has stored" something.',
    positions: ['JTB (Gettier-problematic): knowledge = justified true belief', 'Reliabilist: knowledge = belief produced by reliable processes', 'Pragmatist: knowledge = what works', 'Semantic: knowledge = meaningful information with truth conditions'],
  },
  {
    id: 'PQ6',
    question: 'Can intelligence be fully substrate-independent, or does the physical medium impose irreducible constraints?',
    domain: 'philosophy of mind',
    currentConsensus: 'Functionalism claims full substrate independence. Critics (Searle, Penrose) argue the physical medium imposes constraints — Penrose via quantum effects in microtubules, Searle via biological causal power.',
    tension: 'UTI\'s core claim is substrate-independence. If the physical medium matters for causal power or consciousness, the theory is at best a first-order approximation valid for systems above some complexity threshold.',
    whyItMatters: 'If false, UTI must be revised to include substrate-specific modules at certain stages — significantly complicating the theory.',
    positions: ['Strong functionalism: substrate is fully irrelevant above functional description', 'Weak functionalism: substrate sets bounds but same function can be multiply realized', 'Biological naturalism (Searle): biological substrate confers special causal powers', 'Penrose-Hameroff: quantum coherence in neurons is essential'],
  },
  {
    id: 'PQ7',
    question: 'What is the relationship between increasing complexity and the emergence of new properties?',
    domain: 'complex systems',
    currentConsensus: 'Emergentism: some properties (consciousness, life, intelligence) emerge at higher levels of complexity and cannot be reduced to their constituents. Weak emergence is epistemically irreducible; strong emergence is ontologically irreducible.',
    tension: 'UTI posits 10 stages with phase transitions between them. If stage transitions are merely epistemically emergent, they are predictable in principle and the model is scientifically conservative. If they are strongly emergent, Stage N+1 cannot be predicted from Stage N — threatening the theory\'s predictive value.',
    whyItMatters: 'Determines whether UTI stage transitions are engineering problems (solvable) or natural phase transitions (requiring discovery).',
    positions: ['Reductionism: all emergence is epistemically irreducible but ontologically derivative', 'Weak emergentism: emergent properties are real but in-principle reducible', 'Strong emergentism: some properties are ontologically irreducible', 'Eliminativist: emergence is a placeholder for incomplete reduction'],
  },
]

// ─── Research Topics ───────────────────────────────────────────────────────────
export const researchTopics = [
  {
    id: 'RT1',
    title: 'Structural Intelligence Formalization',
    description: 'Developing a rigorous mathematical definition of intelligence as a structural property of information-processing systems — substrate-independent, compositional, and amenable to comparative measurement across biological and artificial systems.',
    relatedStages: [1, 2, 3, 4],
    relatedPillars: [],
    maturity: 35,
    openProblems: 4,
    tags: ['Formal Theory', 'Mathematics', 'Philosophy'],
    currentWork: 'State-space equation formalism, attractor landscape modeling, category-theoretic foundations.',
    gap: 'No consensus metric for measuring intelligence as a structural property; existing benchmarks (IQ, ARC, MMLU) measure performance, not structure.',
  },
  {
    id: 'RT2',
    title: 'Sensorimotor Grounding of Symbols',
    description: 'Designing and training grounding functions that map high-dimensional perceptual inputs to a structured latent space such that symbolic operations on that space produce semantically coherent results — solving the symbol grounding problem constructively.',
    relatedStages: [5, 6],
    relatedPillars: [1, 2],
    maturity: 42,
    openProblems: 3,
    tags: ['Grounding', 'Representation Learning', 'Embodiment'],
    currentWork: 'Contrastive learning, joint vision-language pretraining, embodied RL in simulation.',
    gap: 'Current grounding methods rely on statistical co-occurrence rather than causal-referential grounding; they fail under distribution shift.',
  },
  {
    id: 'RT3',
    title: 'Temporal Knowledge Graph Architecture',
    description: 'Building a structured episodic memory system that stores, indexes, and retrieves knowledge with temporal provenance, enabling an AI agent to maintain a consistent world model across time, contexts, and conflicting updates.',
    relatedStages: [6, 7],
    relatedPillars: [3],
    maturity: 48,
    openProblems: 3,
    tags: ['Memory', 'Knowledge Graph', 'Temporal Reasoning'],
    currentWork: 'TKG embedding models (TeRo, TNTComplEx), temporal reasoning benchmarks, knowledge graph completion.',
    gap: 'Existing TKG models treat time as a feature rather than a first-class dimension; no architecture supports open-ended temporal horizon with efficient retrieval.',
  },
  {
    id: 'RT4',
    title: 'Causal Reasoning in Adaptive AI Systems',
    description: 'Integrating Pearl\'s causal hierarchy (association → intervention → counterfactual) into the inference pipeline of AI agents, enabling genuine causal understanding rather than statistical pattern recognition.',
    relatedStages: [4, 5, 6],
    relatedPillars: [4],
    maturity: 38,
    openProblems: 4,
    tags: ['Causality', 'Causal Inference', 'Intervention'],
    currentWork: 'Causal representation learning, do-calculus in ML, causal discovery from observational data.',
    gap: 'Integrating causal inference into end-to-end differentiable systems without approximating away the interventional semantics is unsolved.',
  },
  {
    id: 'RT5',
    title: 'Meta-Learning and Architectural Self-Modification',
    description: 'Developing learning algorithms that operate on the learning algorithm itself — enabling an AI system to modify its own inductive biases, architecture, and learning rate schedules based on meta-level performance signals.',
    relatedStages: [7, 8],
    relatedPillars: [5],
    maturity: 52,
    openProblems: 3,
    tags: ['Meta-Learning', 'Self-Modification', 'MAML'],
    currentWork: 'MAML, Reptile, hypernetworks, neural architecture search, learned optimizers.',
    gap: 'Current meta-learning operates over a fixed hypothesis class — no system can modify its own architectural assumptions or increase its representational capacity autonomously.',
  },
  {
    id: 'RT6',
    title: 'Multi-Objective Goal Architecture with Conflict Resolution',
    description: 'Designing goal architectures that maintain hierarchical, potentially conflicting objectives, execute principled conflict resolution strategies, and preserve alignment with high-level goals during lower-level optimization.',
    relatedStages: [6, 7, 8],
    relatedPillars: [6],
    maturity: 30,
    openProblems: 5,
    tags: ['Goal Architecture', 'Alignment', 'Multi-Objective'],
    currentWork: 'Multi-objective RL, constrained optimization, utility function design, reward modeling.',
    gap: 'No principled theory of how to represent, prioritize, and resolve conflicts between heterogeneous objectives without collapsing to scalar reward.',
  },
  {
    id: 'RT7',
    title: 'Cross-Domain Intelligence Transfer',
    description: 'Understanding and operationalizing the conditions under which structural knowledge gained in one domain transfers to a radically different domain — enabling genuine generalization beyond statistical similarity.',
    relatedStages: [3, 7, 9],
    relatedPillars: [5, 7],
    maturity: 45,
    openProblems: 3,
    tags: ['Transfer Learning', 'Generalization', 'Cross-Domain'],
    currentWork: 'Domain adaptation, few-shot learning, foundation models, representation alignment.',
    gap: 'Transfer learning theory is statistical (distribution shift bounds) rather than structural; no framework predicts which structural features transfer and which do not.',
  },
  {
    id: 'RT8',
    title: 'ERP-SIM: Simulation Framework for Intelligence Research',
    description: 'Building a formal simulation environment that instantiates the UTI stages as simulation parameters, enabling controlled experiments on intelligence emergence, phase transitions, and cross-substrate transfer under reproducible conditions.',
    relatedStages: [2, 3, 4, 5],
    relatedPillars: [7],
    maturity: 25,
    openProblems: 4,
    tags: ['Simulation', 'DSR', 'Benchmark'],
    currentWork: 'ERP-SIM framework design; prototype P4 targeting Stage 4 simulation capabilities.',
    gap: 'No existing simulation environment was designed with UTI stage criteria in mind; existing AI benchmarks measure performance, not structural intelligence properties.',
  },
  {
    id: 'RT9',
    title: 'Design Science Research Methodology for Intelligence Theory',
    description: 'Adapting and extending the Design Science Research (DSR) methodology for the unique demands of intelligence theory — where artifacts are theoretical frameworks, not software systems, and evaluation requires both formal proof and empirical testing.',
    relatedStages: [1, 2],
    relatedPillars: [],
    maturity: 60,
    openProblems: 2,
    tags: ['DSR', 'Methodology', 'Philosophy of Science'],
    currentWork: 'DSR framework (Hevner et al.) applied to UTI; design cycle for each stage artifact.',
    gap: 'DSR was designed for information systems, not theoretical science. Extension for theory-building artifacts requires new evaluation criteria.',
  },
  {
    id: 'RT10',
    title: 'Eternal Research Program Governance',
    description: 'Designing the institutional, formal, and incentive structures necessary for a research program to persist, accumulate knowledge cumulatively, and self-govern across multiple generations of researchers — analogous to Lakatos\' scientific research programme but operationally specified.',
    relatedStages: [9, 10],
    relatedPillars: [],
    maturity: 18,
    openProblems: 5,
    tags: ['ERP', 'Governance', 'Institutions', 'Philosophy of Science'],
    currentWork: 'ERP governance model; Lakatosian SRP formalization; succession protocol design.',
    gap: 'No formal theory of research program self-governance exists; existing academic institutions provide no model for cross-generational knowledge accumulation with formal validation.',
  },
]

// ─── Fields ────────────────────────────────────────────────────────────────────
export const fields = [
  {
    id: 'F1',
    name: 'Philosophy of Mind',
    relevance: 'core',
    icon: '🧠',
    contribution: 'Provides the conceptual foundations for consciousness, intentionality, representation, and mental causation — the ontological scaffolding UTI must either incorporate or reject.',
    gap: 'Philosophy of mind lacks formal, mathematically precise models; it generates conceptual distinctions that are not directly testable. UTI bridges this by formalizing the distinctions.',
    keyFigures: ['Searle', 'Dennett', 'Chalmers', 'Clark', 'Merleau-Ponty'],
    relatedRQs: ['RQ1', 'PQ2', 'PQ6'],
  },
  {
    id: 'F2',
    name: 'Cognitive Science',
    relevance: 'core',
    icon: '🔄',
    contribution: 'Bridges psychology, neuroscience, linguistics, and AI to study the mind as an information-processing system. Provides empirical data on human intelligence that constrains UTI\'s formal models.',
    gap: 'Cognitive science is fragmented across disciplines; no unified computational account of general cognition exists. UTI aspires to provide that account.',
    keyFigures: ['Miller', 'Newell & Simon', 'Minsky', 'Fodor', 'Lakoff'],
    relatedRQs: ['RQ1', 'RQ3', 'PQ5'],
  },
  {
    id: 'F3',
    name: 'Artificial Intelligence',
    relevance: 'core',
    icon: '🤖',
    contribution: 'Provides the engineering substrate for UAIF — the computational techniques (ML, RL, NLP, planning) that must be integrated into the UAIF architecture. Also provides empirical evidence of current capability boundaries.',
    gap: 'AI research is largely engineering-driven without a unified theoretical foundation; systems are evaluated by performance metrics rather than structural intelligence properties. UTI aims to fill this theoretical gap.',
    keyFigures: ['Turing', 'McCarthy', 'LeCun', 'Bengio', 'Pearl', 'Minsky'],
    relatedRQs: ['RQ4', 'RQ5', 'RQ6'],
  },
  {
    id: 'F4',
    name: 'Neuroscience',
    relevance: 'supporting',
    icon: '🧬',
    contribution: 'Provides the biological ground truth for intelligence — the substrate whose behavior UTI must be consistent with. Predictive coding, Hebbian plasticity, and attractor networks are key models informing UTI Stages 4–6.',
    gap: 'Neuroscience lacks a systems-level theory connecting neural circuits to cognitive functions; the "explanatory gap" between neurons and behavior is open. UTI does not require neuroscience to close this gap but benefits when it does.',
    keyFigures: ['Friston', 'Hopfield', 'Hebb', 'Dehaene', 'Koch'],
    relatedRQs: ['RQ1', 'RQ3'],
  },
  {
    id: 'F5',
    name: 'Complex Systems Science',
    relevance: 'supporting',
    icon: '🌀',
    contribution: 'Provides the formal tools for studying emergence, self-organization, phase transitions, and cross-scale causation — all central to UTI\'s account of how intelligence arises from simpler components.',
    gap: 'Complex systems science is descriptive more than predictive; it identifies patterns of emergence but lacks a theory of which complex systems develop intelligence. UTI fills this by specifying the structural conditions.',
    keyFigures: ['Holland', 'Wolfram', 'Kauffman', 'Bar-Yam', 'Barabási'],
    relatedRQs: ['PQ7', 'RQ2'],
  },
  {
    id: 'F6',
    name: 'Mathematical Logic & Category Theory',
    relevance: 'supporting',
    icon: '∀',
    contribution: 'Provides the formal language for UTI\'s substrate-independent structural claims. Category theory\'s morphisms and functors offer a natural vocabulary for structural similarity across domains; type theory grounds formal verification.',
    gap: 'Category theory is not yet used in AI system design; the connection between categorical abstractions and neural network architectures is nascent (category-theoretic deep learning is an emerging area).',
    keyFigures: ['Mac Lane', 'Lawvere', 'Fong & Spivak', 'Jacobs', 'Wadler'],
    relatedRQs: ['RQ2', 'PQ3'],
  },
  {
    id: 'F7',
    name: 'Philosophy of Science',
    relevance: 'supporting',
    icon: '⚗️',
    contribution: 'Provides the normative standards for scientific theories — falsifiability (Popper), progressive research programmes (Lakatos), paradigm shifts (Kuhn), and inference to the best explanation (IBE). The Eternal Research Program is modeled on Lakatosian SRP.',
    gap: 'Philosophy of science rarely engages with the specific methodological challenges of intelligence theory — theories that simultaneously aim to be formal, empirical, and engineering-applicable. UTI navigates all three.',
    keyFigures: ['Popper', 'Kuhn', 'Lakatos', 'Feyerabend', 'Laudan'],
    relatedRQs: ['RQ7', 'RQ8', 'PQ1'],
  },
  {
    id: 'F8',
    name: 'Causal Inference',
    relevance: 'supporting',
    icon: '→',
    contribution: 'Pearl\'s causal hierarchy, structural causal models (SCMs), and do-calculus provide the formal language for UAIF\'s causal reasoning module. Potential outcomes framework and propensity score methods inform experimental design.',
    gap: 'Integrating causal inference into end-to-end differentiable AI systems is an open problem; current approaches either approximate causality (attention mechanisms) or treat it as a post-hoc analysis layer.',
    keyFigures: ['Pearl', 'Rubin', 'Peters', 'Schölkopf', 'Bareinboim'],
    relatedRQs: ['RQ3', 'RT4', 'PQ4'],
  },
  {
    id: 'F9',
    name: 'Information Theory',
    relevance: 'adjacent',
    icon: '📡',
    contribution: 'Shannon entropy, mutual information, and Kolmogorov complexity provide quantitative tools for measuring information processing, compression, and representation capacity — grounding UTI\'s informal notion of "compact state representations."',
    gap: 'Information-theoretic measures do not capture semantic content or intentionality; they measure signal structure, not meaning. UTI must combine information theory with a semantic grounding theory.',
    keyFigures: ['Shannon', 'Kolmogorov', 'Chaitin', 'Cover & Thomas', 'Tishby'],
    relatedRQs: ['RQ2', 'PQ5'],
  },
  {
    id: 'F10',
    name: 'Organizational Science',
    relevance: 'adjacent',
    icon: '🏛️',
    contribution: 'Provides models for how intelligence manifests at the organizational scale — distributed cognition, institutional knowledge, collective intelligence, and organizational learning. UTI claims these are instances of the same structural intelligence as biological brains.',
    gap: 'Organizational science has not formally connected organizational behavior to the same mathematical structures as neural or AI intelligence. The connection is claimed by UTI but not yet demonstrated.',
    keyFigures: ['Weick', 'Nonaka', 'Simon', 'March', 'Hutchins'],
    relatedRQs: ['RQ1', 'PQ3'],
  },
]

// ─── Problem Collective ────────────────────────────────────────────────────────
export const MATURITY_LEVELS = [
  { id: 'nascent',    label: 'Nascent',    color: '#f43f5e', bg: '#f43f5e15', range: '0–25%',  desc: 'Problem is identified; no satisfactory solutions exist; basic terminology contested.' },
  { id: 'emerging',  label: 'Emerging',   color: '#f97316', bg: '#f9731615', range: '26–50%', desc: 'Partial solutions exist; problem is well-defined; competing approaches are active.' },
  { id: 'developing',label: 'Developing', color: '#f59e0b', bg: '#f59e0b15', range: '51–75%', desc: 'Dominant approach identified; engineering solutions exist but theoretical gaps remain.' },
  { id: 'mature',    label: 'Mature',     color: '#10b981', bg: '#10b98115', range: '76–100%','desc': 'Well-understood; established solutions; research focus has moved to refinement.' },
]

export const problemCollective = [
  {
    id: 'PC1',
    title: 'The Symbol Grounding Problem',
    description: 'Symbols in computational systems are defined by their relations to other symbols — they have no intrinsic connection to the objects they denote. How can a physical symbol system acquire genuine semantic content?',
    maturity: 'emerging',
    maturityScore: 38,
    relatedStages: [5, 6],
    relatedPillars: [1, 2],
    tags: ['Semantics', 'Representation', 'Embodiment'],
    currentApproaches: [
      'Embodied AI: ground symbols through sensorimotor interaction with environments',
      'Contrastive vision-language pretraining (CLIP, ALIGN): statistical co-occurrence of text and images',
      'Robotic grounding: physical manipulation creates symbol-world links',
    ],
    limitations: [
      'Statistical co-occurrence is not causal-referential grounding',
      'Embodied approaches are expensive and don\'t generalize compositionally',
      'No grounding approach survives significant distribution shift',
    ],
    utiRelevance: 'UTI Stage 05 (ERP-X: Cross-Domain Transfer) requires grounding to enable transfer; UAIF Pillar 2 (Grounding Function) is the architectural response to this problem.',
  },
  {
    id: 'PC2',
    title: 'The Frame Problem',
    description: 'How does an intelligent system know which parts of its world model to update when an action is performed, and which parts can be assumed to remain constant — without explicitly reasoning about every possible unchanged fact?',
    maturity: 'emerging',
    maturityScore: 32,
    relatedStages: [4, 6],
    relatedPillars: [3, 4],
    tags: ['Representation', 'Reasoning', 'World Models'],
    currentApproaches: [
      'Default logic and non-monotonic reasoning in symbolic AI',
      'Learned world models (Dreamer, World Models): neural implicit frames',
      'Attention mechanisms: implicit relevance weighting',
    ],
    limitations: [
      'Default logic is computationally intractable for large state spaces',
      'Learned world models cannot provide formal guarantees about frame handling',
      'Attention is not selective reasoning — it is weighted averaging over all inputs',
    ],
    utiRelevance: 'Stage 04 (Structural Intelligence) requires formal state update rules; UAIF TKG architecture must implement efficient partial-world-model updates.',
  },
  {
    id: 'PC3',
    title: 'Common Sense Reasoning',
    description: 'Humans effortlessly make thousands of inferences daily based on unstated background knowledge about physics, psychology, social norms, and causal regularities. How can AI systems acquire and deploy this tacit knowledge?',
    maturity: 'emerging',
    maturityScore: 42,
    relatedStages: [3, 5, 6],
    relatedPillars: [2, 3],
    tags: ['Reasoning', 'Knowledge', 'Tacit Knowledge'],
    currentApproaches: [
      'Large-scale knowledge graphs (ConceptNet, ATOMIC) encoding common-sense facts',
      'LLM pretraining on internet text implicitly encodes common-sense regularities',
      'Neuro-symbolic integration: neural pattern recognition + symbolic inference',
    ],
    limitations: [
      'Knowledge graphs are manually curated and brittle to paraphrase',
      'LLM common-sense is statistical and fails on novel combinations',
      'Neuro-symbolic approaches face integration bottlenecks',
    ],
    utiRelevance: 'Stage 03 (Cross-Domain Intelligence Convergence) identifies common-sense as a structural invariant across domains; UAIF must operationalize it as a grounded reasoning module.',
  },
  {
    id: 'PC4',
    title: 'Robust Transfer Learning Across Domains',
    description: 'Current transfer learning is brittle: systems fine-tuned on one domain perform poorly when the distribution shifts, even slightly. How can a system learn structural invariants that transfer reliably across radically different domains?',
    maturity: 'developing',
    maturityScore: 55,
    relatedStages: [3, 7, 9],
    relatedPillars: [5, 7],
    tags: ['Transfer', 'Generalization', 'Distribution Shift'],
    currentApproaches: [
      'Domain adaptation and domain generalization techniques',
      'Foundation model pretraining (GPT, BERT, SAM): large-scale pretraining enables in-context transfer',
      'Meta-learning (MAML): learn to learn quickly in new domains',
    ],
    limitations: [
      'Foundation model transfer is statistical — it works when source and target domains overlap in training data',
      'No theory predicts when transfer will succeed or fail based on structural domain properties',
      'Meta-learning requires task distributions at meta-training time; open-ended transfer is unsolved',
    ],
    utiRelevance: 'Stage 03 identifies structural convergence as the mechanism for transfer; UTI predicts transfer succeeds when structural invariants are preserved — a testable claim.',
  },
  {
    id: 'PC5',
    title: 'Causal Discovery from Observational Data',
    description: 'Given only observational data — without intervention — can an AI system infer the causal structure of its environment? Correlation is cheap; causation is expensive (requires intervention). How can causal structure be recovered without intervening?',
    maturity: 'developing',
    maturityScore: 50,
    relatedStages: [4, 5],
    relatedPillars: [4],
    tags: ['Causality', 'Causal Discovery', 'Interventions'],
    currentApproaches: [
      'PC algorithm and variants (constraint-based causal discovery)',
      'LiNGAM (Independent Component Analysis for causal graphs)',
      'Differentiable causal discovery (NOTEARS, DAG-GNN)',
    ],
    limitations: [
      'All methods make strong assumptions (Markov, faithfulness, acyclicity) that often fail in practice',
      'Scaling to high-dimensional systems is computationally intractable',
      'Observational methods cannot distinguish between Markov-equivalent structures',
    ],
    utiRelevance: 'UAIF Pillar 4 requires causal discovery from environment interaction; Stage 05 requires identifying structural causal models across domains.',
  },
  {
    id: 'PC6',
    title: 'Long-Horizon Episodic Memory Architecture',
    description: 'How can an AI system maintain a structured, queryable memory of past experiences over arbitrarily long time horizons without catastrophic forgetting, and retrieve relevant memories efficiently in context?',
    maturity: 'nascent',
    maturityScore: 28,
    relatedStages: [6, 7],
    relatedPillars: [3],
    tags: ['Memory', 'Catastrophic Forgetting', 'Retrieval'],
    currentApproaches: [
      'Experience replay (ER) and variants: replay buffer for stability',
      'Episodic memory in RL (EMDQN, Episodic RL)',
      'Retrieval-augmented generation (RAG): external vector store as memory',
    ],
    limitations: [
      'Experience replay scales poorly with time horizon; memory is unstructured',
      'RAG retrieves based on embedding similarity, not temporal or causal relevance',
      'No architecture supports structured episodic memory with temporal indexing and causal chain retrieval',
    ],
    utiRelevance: 'UAIF Pillar 3 (TKG-Augmented Memory) is designed as the architectural solution to this problem; Stage 06 instantiates it as a required capability.',
  },
  {
    id: 'PC7',
    title: 'Goal Specification and Alignment',
    description: 'How do we specify what we want an AI system to do in a way that is complete, consistent, and robust to distributional shift — and how do we ensure the system continues to optimize for the intended goal as it becomes more capable?',
    maturity: 'emerging',
    maturityScore: 35,
    relatedStages: [7, 8, 9],
    relatedPillars: [6],
    tags: ['Alignment', 'Goal Specification', 'Safety'],
    currentApproaches: [
      'RLHF (RL from Human Feedback): learn reward model from human preferences',
      'Constitutional AI: specify constraints and train to follow them',
      'Inverse RL: infer goals from demonstrated behavior',
    ],
    limitations: [
      'RLHF reward models are approximate and can be gamed by optimizers',
      'Constitutional constraints are underspecified and conflict in edge cases',
      'Inverse RL is ambiguous: many goal functions explain the same behavior',
    ],
    utiRelevance: 'Stage 07 (UAIF Implementation) requires a formal goal architecture with multi-objective conflict resolution; this is the hardest unsolved problem for UAIF Pillar 6.',
  },
  {
    id: 'PC8',
    title: 'Intelligence Measurement and Structural Benchmarking',
    description: 'Current AI benchmarks measure task-specific performance (accuracy, F1, pass@k) rather than structural intelligence properties. How can we measure whether a system has achieved a given UTI stage rather than merely performing well on associated tasks?',
    maturity: 'nascent',
    maturityScore: 22,
    relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    relatedPillars: [7],
    tags: ['Benchmarks', 'Measurement', 'Evaluation'],
    currentApproaches: [
      'ARC (Abstraction and Reasoning Corpus): tests pattern generalization',
      'BIG-Bench: diverse capability evaluation',
      'MMLU: knowledge breadth',
    ],
    limitations: [
      'All existing benchmarks are behavioral; none assess the structural properties UTI specifies',
      'Performance on benchmarks can be achieved by superficial statistical fitting without structural intelligence',
      'No benchmark is designed to test falsifiable predictions of a stage-based theory',
    ],
    utiRelevance: 'UTI Stage 02 requires formal benchmarks for measuring structural intelligence; creating stage-appropriate benchmarks is a primary research output of the UTI program.',
  },
  {
    id: 'PC9',
    title: 'Stable Recursive Self-Improvement',
    description: 'How can an AI system improve its own architecture, learning algorithms, or objective functions in a manner that is formally guaranteed to be stable, convergent, and aligned with the original goal — without requiring external supervision at each step?',
    maturity: 'nascent',
    maturityScore: 15,
    relatedStages: [8, 9],
    relatedPillars: [5],
    tags: ['Self-Improvement', 'Stability', 'Meta-Learning'],
    currentApproaches: [
      'MAML and gradient-based meta-learning: learn to adapt quickly',
      'Neural architecture search: automated architecture improvement',
      'Self-play and curriculum learning: progressive self-challenge',
    ],
    limitations: [
      'No existing system modifies its own objective function safely',
      'Recursive self-improvement beyond one meta-level is unstable in current implementations',
      'Formal stability guarantees for self-modifying systems are an open mathematical problem',
    ],
    utiRelevance: 'Stage 08 (Meta-Learning) and Stage 09 (ERP) both require stable self-modification; UAIF Pillar 5 is the partial architectural response.',
  },
  {
    id: 'PC10',
    title: 'Substrate-Independent Formalization of Intelligence',
    description: 'How can a mathematical theory describe intelligence in a way that is genuinely substrate-independent — applicable to neurons, transistors, markets, and ecosystems — without reducing to a mere analogy or losing empirical content?',
    maturity: 'nascent',
    maturityScore: 20,
    relatedStages: [1, 2, 3, 4],
    relatedPillars: [],
    tags: ['Formal Theory', 'Substrate Independence', 'Philosophy'],
    currentApproaches: [
      'Active Inference (Friston): free energy minimization as universal intelligence principle',
      'Universal Intelligence (Legg & Hutter): AIXI formalism over all computable environments',
      'Integrated Information Theory (Tononi): phi as substrate-independent consciousness/intelligence measure',
    ],
    limitations: [
      'Active Inference requires a specific Bayesian generative model structure — not all intelligence fits this mold',
      'AIXI is uncomputable — it is theoretically important but practically inapplicable',
      'IIT\'s phi measure is exponentially expensive to compute and doesn\'t obviously connect to engineering',
    ],
    utiRelevance: 'This is the core problem that UTI is designed to solve; Stages 01–04 collectively build toward the substrate-independent formalization that later stages operationalize.',
  },
]
