export const dimensions = [
  {
    id: 'intelligence-types',
    title: 'Intelligence Classification',
    icon: '🧠',
    accent: '#8b5cf6',
    description: 'A hierarchy of intelligence from narrow domain-specific systems to substrate-independent universal intelligence.',
    nodes: [
      {
        id: 'narrow-ai',
        label: 'Narrow Domain Intelligence',
        tier: 1,
        maturity: 'Deployed',
        description: 'Systems optimized for a single, well-defined task within one domain. Cannot generalize across domains or transfer skills to novel problems.',
        examples: ['Chess engines (Stockfish)', 'Protein folding (AlphaFold)', 'Image classification (ResNet)', 'Market prediction models'],
        utiStages: [1],
        uaiPillars: [1],
        children: ['statistical-learning'],
      },
      {
        id: 'statistical-learning',
        label: 'Statistical Learning Systems',
        tier: 2,
        maturity: 'Deployed',
        description: 'Foundation models trained on internet-scale data. Generalize across surface-level tasks through statistical compression, but lack persistent memory, causal reasoning, and temporal continuity.',
        examples: ['GPT-4 / Claude / Gemini', 'CLIP (multimodal)', 'Stable Diffusion', 'Code LLMs'],
        utiStages: [2],
        uaiPillars: [1, 2],
        children: ['epistemic-ai'],
      },
      {
        id: 'epistemic-ai',
        label: 'Epistemic Intelligence',
        tier: 3,
        maturity: 'Early Research',
        description: 'Systems that maintain persistent knowledge structures, model uncertainty, and can reflect on the limits of their own knowledge. Bridges statistical and symbolic paradigms.',
        examples: ['RAG systems with KG backends', 'GraphRAG', 'MemoryBank', 'LangGraph agents'],
        utiStages: [3],
        uaiPillars: [3, 4, 6],
        children: ['structural-intelligence'],
      },
      {
        id: 'structural-intelligence',
        label: 'Structural Intelligence',
        tier: 4,
        maturity: 'Theoretical',
        description: 'Systems that reason over the formal structure of knowledge — graph topology, invariants, category-theoretic mappings — enabling cross-domain structural analogy and transfer.',
        examples: ['Graph neural networks (GNNs)', 'Causal discovery systems', 'Cross-domain analogy engines'],
        utiStages: [4],
        uaiPillars: [3, 4, 5],
        children: ['causal-intelligence'],
      },
      {
        id: 'causal-intelligence',
        label: 'Causal Intelligence',
        tier: 5,
        maturity: 'Theoretical',
        description: 'Systems that model causal mechanisms, not just correlations. Can perform interventions, compute counterfactuals, and reason about the effects of actions before taking them.',
        examples: ["Pearl's do-calculus engines", 'Causal Bayesian networks', 'Structural causal models (SCMs)'],
        utiStages: [4, 5],
        uaiPillars: [5],
        children: ['universal-intelligence'],
      },
      {
        id: 'universal-intelligence',
        label: 'Universal Substrate-Independent Intelligence',
        tier: 6,
        maturity: 'Vision',
        description: 'The UAIF target: intelligence that operates identically across computational, biological, social, and organizational substrates. Defined by the architecture, not the medium.',
        examples: ['UAIF / ELG (proposed)', 'Biological brains', 'Scientific communities (as collective intelligence)'],
        utiStages: [8, 9, 10],
        uaiPillars: [7],
        children: [],
      },
    ],
  },

  {
    id: 'cognitive-operations',
    title: 'Cognitive Operations',
    icon: '⚙️',
    accent: '#f59e0b',
    description: 'The fundamental operations that an intelligent system must perform, ordered by cognitive complexity.',
    nodes: [
      {
        id: 'perception',
        label: 'Perception & Encoding',
        tier: 1,
        maturity: 'Deployed',
        description: 'Converting raw sensory input (text, image, audio, sensor data) into dense latent representations that preserve semantic content for downstream processing.',
        formalDef: 'Lₜ = Encoder(Oₜ)',
        examples: ['Transformer self-attention', 'CLIP vision-language encoding', 'Sensor fusion in robotics'],
        utiStages: [2],
        uaiPillars: [2],
      },
      {
        id: 'grounding',
        label: 'Semantic Grounding',
        tier: 2,
        maturity: 'Active Research',
        description: 'Mapping continuous latent representations to discrete symbolic entities with persistent identity. The neural-to-symbolic bridge that gives symbols meaning through perceptual anchoring.',
        formalDef: 'Γ: Lₜ → Eₜ  (P(Eᵢ | Lₜ, Hₜ, Cₜ))',
        examples: ['Named entity recognition + linking', 'Coreference resolution', 'Visual grounding (referring expressions)'],
        utiStages: [3],
        uaiPillars: [3],
      },
      {
        id: 'world-modeling',
        label: 'World-Model Construction',
        tier: 3,
        maturity: 'Active Research',
        description: 'Maintaining a persistent, structured, temporally-indexed model of all known entities, their attributes, relationships, and how they evolve over time.',
        formalDef: 'Sₜ = (Eₜ, Rₜ, Lₜ, Cₜ, Uₜ, Gₜ)',
        examples: ['Temporal knowledge graphs', 'NELL continual KB construction', 'Robotic scene graphs'],
        utiStages: [3, 4],
        uaiPillars: [4],
      },
      {
        id: 'causal-reasoning',
        label: 'Causal Reasoning',
        tier: 4,
        maturity: 'Theoretical / Prototype',
        description: 'Computing interventional and counterfactual distributions over a causal model. Operating at the second and third rungs of Pearl\'s Ladder — beyond mere correlation.',
        formalDef: 'P(Sₜ₊₁ | do(Aₜ), Sₜ)',
        examples: ["Pearl's do-calculus", 'Causal discovery (PC algorithm)', 'Counterfactual NLU datasets'],
        utiStages: [4, 6],
        uaiPillars: [5],
      },
      {
        id: 'memory-mgmt',
        label: 'Memory Management',
        tier: 5,
        maturity: 'Active Research',
        description: 'Selectively storing, consolidating, retrieving, and forgetting knowledge. Balancing fidelity of episodic traces with efficiency of semantic generalization.',
        formalDef: 'I(Eᵢ) = f(usage, causality, relevance, novelty)',
        examples: ['MemoryBank', 'Generative replay (Shin et al.)', 'Elastic weight consolidation (EWC)'],
        utiStages: [3, 7],
        uaiPillars: [6],
      },
      {
        id: 'meta-cognition',
        label: 'Meta-Cognition',
        tier: 6,
        maturity: 'Theoretical',
        description: 'The system\'s capacity to model its own knowledge state: knowing what it knows, identifying gaps, monitoring reasoning quality, and directing attention to resolve uncertainty.',
        formalDef: 'Mₜ = Model(Sₜ)',
        examples: ['Calibrated uncertainty estimation', 'Self-critique agents (Reflexion)', 'Active learning query strategies'],
        utiStages: [7, 8],
        uaiPillars: [7],
      },
      {
        id: 'goal-attention',
        label: 'Goal-Directed Attention',
        tier: 7,
        maturity: 'Theoretical',
        description: 'The policy that allocates perceptual and computational resources toward observations, queries, and memory operations most relevant to current goals.',
        formalDef: 'Πₜ: Sₜ × Gₜ → Action space',
        examples: ['Active learning', 'Curiosity-driven exploration', 'Goal-conditioned RL agents'],
        utiStages: [8, 9],
        uaiPillars: [7],
      },
    ],
  },

  {
    id: 'knowledge-representations',
    title: 'Knowledge Representation',
    icon: '📦',
    accent: '#10b981',
    description: 'The formal structures used to encode and store knowledge about the world, ordered by expressiveness and computational cost.',
    nodes: [
      {
        id: 'vector-embeddings',
        label: 'Vector Embeddings',
        tier: 1,
        maturity: 'Deployed',
        description: 'Dense floating-point vectors encoding semantic content in high-dimensional space. Fast to compute and retrieve; poor at logical inference and relational reasoning.',
        examples: ['Word2Vec / GloVe', 'Sentence transformers (SBERT)', 'Dense retrieval vectors (DPR)'],
        tradeoffs: 'Fast retrieval, no logical structure, no temporal indexing',
        utiStages: [2],
        uaiPillars: [2],
      },
      {
        id: 'property-graphs',
        label: 'Property Graphs',
        tier: 2,
        maturity: 'Deployed',
        description: 'Directed graphs where nodes and edges carry typed property bags. Enables relational queries (Cypher, GSQL) and explicit entity-relationship reasoning.',
        examples: ['Neo4j', 'Amazon Neptune', 'TigerGraph', 'Wikidata'],
        tradeoffs: 'Relational queries, no temporal indexing, no probabilistic reasoning',
        utiStages: [3],
        uaiPillars: [4],
      },
      {
        id: 'temporal-kgs',
        label: 'Temporal Knowledge Graphs',
        tier: 3,
        maturity: 'Active Research',
        description: 'Property graphs with timestamped facts and temporal edge attributes. Enables time-indexed queries and state trajectory reasoning. The ELG\'s core data structure.',
        examples: ['YAGO-3 (temporal)', 'T-KGR framework', 'Wikidata temporal properties', 'ELG TKG (proposed)'],
        tradeoffs: 'Temporal queries, complex schema management, high write overhead',
        utiStages: [3, 4],
        uaiPillars: [4],
      },
      {
        id: 'causal-graphs',
        label: 'Causal / Structural Causal Models',
        tier: 4,
        maturity: 'Theoretical / Research',
        description: 'Directed acyclic graphs (DAGs) encoding causal dependencies between variables. Support interventional and counterfactual queries beyond observational conditioning.',
        examples: ["Pearl's Bayesian networks", 'Structural causal models (SCMs)', 'Causal discovery outputs (PC, FCI)'],
        tradeoffs: 'Causal inference, requires causal discovery, computationally expensive',
        utiStages: [4, 6],
        uaiPillars: [5],
      },
      {
        id: 'ontologies',
        label: 'Ontologies & Type Hierarchies',
        tier: 2,
        maturity: 'Deployed',
        description: 'Formal specifications of entity types, relation types, and their constraints. Provide the schema layer for knowledge graphs and grounding systems.',
        examples: ['OWL / RDF / RDFS', 'Schema.org', 'UMLS (medical)', 'FIBO (financial)'],
        tradeoffs: 'Type safety, hard to evolve, requires expert curation',
        utiStages: [3, 4],
        uaiPillars: [3],
      },
      {
        id: 'probabilistic-models',
        label: 'Probabilistic World Models',
        tier: 4,
        maturity: 'Theoretical',
        description: 'Distributions over world states encoding uncertainty about entity attributes and relation existence. Enable uncertainty propagation through reasoning chains.',
        examples: ['Markov Logic Networks', 'Probabilistic soft logic (PSL)', 'Uₜ component of UAIF state'],
        tradeoffs: 'Uncertainty representation, inference intractable at scale',
        utiStages: [4, 5],
        uaiPillars: [4, 5],
      },
    ],
  },

  {
    id: 'reasoning-paradigms',
    title: 'Reasoning Paradigms',
    icon: '🔍',
    accent: '#f43f5e',
    description: "How intelligent systems draw conclusions — from statistical pattern matching through causal intervention to counterfactual imagination. Pearl's Ladder is the organizing framework.",
    nodes: [
      {
        id: 'association',
        label: 'Associative Reasoning (Rung 1)',
        tier: 1,
        maturity: 'Deployed',
        description: "Pearl's first rung: observing statistical regularities in data. 'X tends to co-occur with Y.' All current LLMs operate primarily at this level.",
        formalDef: 'P(Y | X)',
        examples: ['LLM next-token prediction', 'Correlation-based recommendation', 'Pattern-matching classification'],
        limitation: 'Cannot distinguish correlation from causation; unreliable out-of-distribution',
        utiStages: [2],
        uaiPillars: [1],
      },
      {
        id: 'abductive',
        label: 'Abductive Reasoning',
        tier: 2,
        maturity: 'Active Research',
        description: 'Inference to the best explanation: given observations, find the most plausible hypothesis that accounts for them. Essential for diagnosis and root cause analysis.',
        formalDef: 'argmax_H P(H | O)',
        examples: ['Medical differential diagnosis', 'Fault localization in systems', 'Scientific hypothesis generation'],
        limitation: 'Hypothesis space must be bounded; computationally expensive',
        utiStages: [3, 6],
        uaiPillars: [5],
      },
      {
        id: 'deductive',
        label: 'Deductive / Logical Reasoning',
        tier: 2,
        maturity: 'Research',
        description: 'Deriving conclusions that necessarily follow from premises. The foundation of formal verification, theorem proving, and symbolic AI.',
        formalDef: 'KB ⊢ Q (KB entails query Q)',
        examples: ['Lean 4 theorem provers', 'Prolog logic programming', 'Answer Set Programming'],
        limitation: 'Requires complete, consistent, formal knowledge bases',
        utiStages: [4, 9],
        uaiPillars: [5],
      },
      {
        id: 'interventional',
        label: 'Interventional Reasoning (Rung 2)',
        tier: 3,
        maturity: 'Theoretical / Prototype',
        description: "Pearl's second rung: predicting the effect of deliberate interventions. 'What would happen if we forced X to be x?' Requires a causal model, not just observational data.",
        formalDef: 'P(Y | do(X=x))',
        examples: ["Pearl's do-calculus", 'Causal effect estimation', 'A/B testing with causal adjustment'],
        limitation: 'Requires causal graph identification; confounders can invalidate estimates',
        utiStages: [6],
        uaiPillars: [5],
      },
      {
        id: 'counterfactual',
        label: 'Counterfactual Reasoning (Rung 3)',
        tier: 4,
        maturity: 'Theoretical',
        description: "Pearl's third rung: reasoning about what would have happened in a world that didn't occur. 'If X had been different, what would Y have been?' Requires abduction + intervention + prediction.",
        formalDef: 'P(Yₓ | x′, Y=y)',
        examples: ['Counterfactual NLI datasets', 'Structural causal model inference', 'Policy evaluation via counterfactuals'],
        limitation: 'Fundamentally unobservable; requires strong causal model assumptions',
        utiStages: [6, 8],
        uaiPillars: [5],
      },
      {
        id: 'analogical',
        label: 'Analogical / Structural Reasoning',
        tier: 3,
        maturity: 'Theoretical / Prototype',
        description: 'Identifying structural similarities between different domains and transferring relational patterns across domain boundaries. The foundation of cross-domain intelligence.',
        formalDef: 'T: StructA → StructB (structure-preserving map)',
        examples: ['ERP-X cross-domain transfer', 'Category-theoretic functors', 'Graph isomorphism matching'],
        limitation: 'Structural similarity does not guarantee semantic equivalence',
        utiStages: [5, 6],
        uaiPillars: [3, 7],
      },
    ],
  },

  {
    id: 'memory-types',
    title: 'Memory Architecture Taxonomy',
    icon: '💾',
    accent: '#3b82f6',
    description: 'The biologically-inspired memory systems that together constitute the ELG\'s knowledge management layer, each serving a distinct temporal and computational role.',
    nodes: [
      {
        id: 'sensory-buffer',
        label: 'Sensory Buffer',
        tier: 1,
        maturity: 'Deployed',
        description: 'Ultra-short-term storage of raw perceptual input before encoding. Milliseconds to seconds. Analogous to the visual and auditory iconic stores in human cognition.',
        capacity: 'High fidelity, very short duration',
        biologicalAnalog: 'Sensory registers (Sperling, 1960)',
        utiStages: [2],
        uaiPillars: [2],
      },
      {
        id: 'working-memory',
        label: 'Working Memory (Context Window)',
        tier: 2,
        maturity: 'Deployed',
        description: 'Active, immediately accessible knowledge for current task execution. In LLMs, this is the context window. In humans, the phonological loop and visuospatial sketchpad.',
        capacity: 'Limited capacity (7±2 chunks; ~128K tokens for LLMs)',
        biologicalAnalog: 'Baddeley\'s working memory model (1974)',
        utiStages: [2],
        uaiPillars: [2, 3],
      },
      {
        id: 'episodic-memory',
        label: 'Episodic Memory',
        tier: 3,
        maturity: 'Active Research',
        description: 'Time-stamped records of specific events and experiences. "At t=142, Engine_A exhibited vibration pattern V_3 under load L_7." High fidelity, temporally indexed, eventually consolidated.',
        capacity: 'Unlimited (external storage), indexed by entity, time, event type',
        biologicalAnalog: 'Hippocampal episodic encoding (O\'Keefe & Nadel, 1978)',
        utiStages: [3],
        uaiPillars: [6],
      },
      {
        id: 'semantic-memory',
        label: 'Semantic Memory',
        tier: 4,
        maturity: 'Active Research',
        description: 'Decontextualized, abstracted facts extracted from multiple episodic traces. "Engine_A is prone to vibration under loads exceeding 75% capacity." Compact, efficiently queryable.',
        capacity: 'Compressed from episodes; proportional to consolidated knowledge',
        biologicalAnalog: 'Neocortical semantic networks (McClelland et al., 1995)',
        utiStages: [3, 7],
        uaiPillars: [6],
      },
      {
        id: 'procedural-memory',
        label: 'Procedural Memory',
        tier: 5,
        maturity: 'Theoretical',
        description: 'Compiled action-outcome patterns for frequently-executed reasoning chains. "When Engine_A overheats → reduce load → schedule maintenance." Fastest to execute, hardest to inspect.',
        capacity: 'Proportional to frequency of causal chain execution',
        biologicalAnalog: 'Basal ganglia procedural learning (Graybiel, 1998)',
        utiStages: [7, 8],
        uaiPillars: [6],
      },
      {
        id: 'collective-memory',
        label: 'Collective / Institutional Memory',
        tier: 6,
        maturity: 'Theoretical',
        description: 'Memory distributed across a community of agents — the knowledge encoded in shared literature, protocols, cultural practices, and institutional structures. The ERP operating at social scale.',
        capacity: 'Civilization-scale; encoded in publications, codebases, cultural artifacts',
        biologicalAnalog: 'Extended mind thesis (Clark & Chalmers, 1998)',
        utiStages: [10],
        uaiPillars: [7],
      },
    ],
  },

  {
    id: 'mathematical-frameworks',
    title: 'Mathematical Frameworks',
    icon: '∑',
    accent: '#d946ef',
    description: 'The formal mathematical languages used across UTI/UAIF to describe, analyze, and compute intelligent behavior.',
    nodes: [
      {
        id: 'information-theory',
        label: 'Information Theory',
        maturity: 'Foundational',
        description: "Shannon's framework for quantifying information as entropy H(X) = -Σ p(x) log p(x). Provides the language for measuring knowledge compression, uncertainty, and information flow across the UAIF pipeline.",
        keyTools: ['Entropy', 'Mutual information', 'KL divergence', 'Channel capacity'],
        utiStages: [1],
        uaiPillars: [2, 6],
      },
      {
        id: 'probability-theory',
        label: 'Probability Theory & Bayesian Inference',
        maturity: 'Foundational',
        description: "The language of uncertainty. Bayesian inference P(H|D) ∝ P(D|H)P(H) underlies entity grounding, uncertainty distributions Uₜ, and the probabilistic world model. All uncertain beliefs in UAIF are probability distributions.",
        keyTools: ['Bayes\' theorem', 'Markov chains', 'MCMC sampling', 'Variational inference'],
        utiStages: [2, 3],
        uaiPillars: [3, 4],
      },
      {
        id: 'graph-theory',
        label: 'Graph Theory & Spectral Methods',
        maturity: 'Core Tool',
        description: 'The mathematics of relational structure. Graph Laplacians, eigenvalues, and spectral embeddings provide the tools for analyzing TKG structure, finding structural invariants, and computing cross-domain similarities.',
        keyTools: ['Graph Laplacian', 'Spectral clustering', 'Graph isomorphism', 'Shortest path algorithms'],
        utiStages: [4],
        uaiPillars: [4, 3],
      },
      {
        id: 'causal-calculus',
        label: "Pearl's do-Calculus",
        maturity: 'Core Tool',
        description: 'The formal language for causal inference. Three rules for computing interventional distributions P(Y|do(X)) from observational data and causal graphs. The foundation of the UAIF causal reasoning engine.',
        keyTools: ['do-operator', 'Backdoor criterion', 'Front-door criterion', 'ID algorithm'],
        utiStages: [4, 6],
        uaiPillars: [5],
      },
      {
        id: 'category-theory',
        label: 'Category Theory',
        maturity: 'Advanced Tool',
        description: "The mathematics of structure-preserving transformations. Functors F: C → D map between categories while preserving structural relationships — the formal language for ERP-X's cross-domain transfer operator T(A → B).",
        keyTools: ['Categories, functors, natural transformations', 'Adjunctions', 'Monads', 'Limits and colimits'],
        utiStages: [4, 5],
        uaiPillars: [3, 7],
      },
      {
        id: 'dynamical-systems',
        label: 'Dynamical Systems Theory',
        maturity: 'Core Tool',
        description: 'The mathematics of systems that evolve over time. Attractors, bifurcations, and phase portraits describe how world states Sₜ evolve — providing the theoretical language for the UAIF state evolution law.',
        keyTools: ['Attractors and basins', 'Lyapunov stability', 'Phase portraits', 'Bifurcation diagrams'],
        utiStages: [4, 5, 8],
        uaiPillars: [4, 7],
      },
      {
        id: 'optimal-transport',
        label: 'Optimal Transport',
        maturity: 'Specialized Tool',
        description: "Wasserstein distances and transport maps provide the framework for ERP-X's domain alignment — finding minimum-cost mappings between probability distributions across different representation spaces.",
        keyTools: ['Wasserstein distance', 'Sinkhorn algorithm', 'Earth Mover\'s distance', 'Monge map'],
        utiStages: [5],
        uaiPillars: [3],
      },
      {
        id: 'type-theory',
        label: 'Dependent Type Theory',
        maturity: 'Advanced Tool',
        description: 'The foundation of formal verification and proof assistants (Lean 4, Coq). Provides the language for UTI Stage 09 self-verifying intelligence — proofs as programs, propositions as types.',
        keyTools: ['Propositions as types', 'Proof terms', 'Lean 4 / Coq / Agda', 'Homotopy type theory'],
        utiStages: [9],
        uaiPillars: [7],
      },
    ],
  },

  {
    id: 'substrates',
    title: 'Intelligence Substrates',
    icon: '🌐',
    accent: '#14b8a6',
    description: 'The physical and organizational substrates that can instantiate intelligence according to the UAIF substrate-independence claim.',
    nodes: [
      {
        id: 'biological-neural',
        label: 'Biological Neural Networks',
        maturity: 'Existence Proof',
        description: 'The reference implementation: mammalian brains. Wetware running on ~20W. Demonstrates persistent world models, causal reasoning, episodic memory, and continual learning at scales current AI cannot match.',
        scaleRange: '10¹⁰ – 10¹¹ neurons, ~10¹⁴ synapses',
        utiStages: [1, 8],
        uaiPillars: [7],
      },
      {
        id: 'computational-digital',
        label: 'Digital Computational Substrates',
        maturity: 'Primary Target',
        description: 'Silicon-based compute: CPUs, GPUs, TPUs, and neuromorphic chips. The primary implementation substrate for the UAIF/ELG architecture and all four prototype targets (P1–P4).',
        scaleRange: 'Edge (1W) to datacenter clusters (MW)',
        utiStages: [2, 3, 4],
        uaiPillars: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        id: 'social-organizations',
        label: 'Social Organizations',
        maturity: 'Theoretical',
        description: 'Companies, research groups, and governance bodies as collective intelligence substrates. Organizational memory, decision protocols, and knowledge-sharing channels implement UAIF components at social scale.',
        scaleRange: 'Teams (10) to corporations (10⁶ people)',
        utiStages: [1, 10],
        uaiPillars: [7],
      },
      {
        id: 'scientific-communities',
        label: 'Scientific Communities',
        maturity: 'Theoretical',
        description: 'The ERP as a collective intelligence substrate: papers as episodic memory, textbooks as semantic memory, experimental protocols as procedural memory, peer review as belief revision.',
        scaleRange: 'Laboratory (10) to global field (10⁵ researchers)',
        utiStages: [10],
        uaiPillars: [6, 7],
      },
      {
        id: 'hybrid-systems',
        label: 'Hybrid Neuro-Symbolic Systems',
        maturity: 'Active Research',
        description: 'Systems combining neural perceptual encoding with symbolic reasoning over explicit knowledge structures. The immediate implementation target of the UAIF — leveraging deep learning strengths while adding symbolic grounding and causal inference.',
        scaleRange: 'System scale; combines model parameters + graph DB + causal engine',
        utiStages: [3, 4, 5],
        uaiPillars: [2, 3, 4, 5, 6],
      },
    ],
  },

  {
    id: 'research-paradigms',
    title: 'Research Paradigms',
    icon: '🔬',
    accent: '#6366f1',
    description: 'The methodological approaches used across the UTI research program to build, test, and validate components of the unified theory.',
    nodes: [
      {
        id: 'constructive-research',
        label: 'Constructive / Design Science',
        maturity: 'Primary Method',
        description: 'Contribution by building: the UAIF framework and ELG architecture are artifacts whose value is demonstrated by their properties and capabilities, not just theorems about them. Knowledge is created through the construction process.',
        outputs: ['UAIF architecture specification', 'ELG prototype implementations', 'Formal framework definitions'],
        utiStages: [3, 4, 5],
        uaiPillars: [7],
      },
      {
        id: 'empirical-ai',
        label: 'Empirical Machine Learning Research',
        maturity: 'Core Method',
        description: 'Controlled experiments comparing system capabilities under different conditions. Benchmark evaluations, ablation studies, and statistical hypothesis testing over model outputs.',
        outputs: ['Benchmark results (HELM, HotpotQA, ARC)', 'Ablation studies', 'Scaling curves'],
        utiStages: [2, 3, 6, 7],
        uaiPillars: [2, 3, 4, 5, 6],
      },
      {
        id: 'theoretical-analysis',
        label: 'Theoretical / Mathematical Analysis',
        maturity: 'Core Method',
        description: 'Formal proofs, complexity bounds, and mathematical characterizations of intelligence components. Provides guarantees that empirical results alone cannot give.',
        outputs: ['Convergence proofs', 'Identifiability conditions', 'Complexity bounds', 'Formal UAIF specification'],
        utiStages: [4, 8, 9],
        uaiPillars: [5, 7],
      },
      {
        id: 'agent-based-simulation',
        label: 'Agent-Based Simulation',
        maturity: 'Specialized Method',
        description: 'Studying emergent behavior in simulated multi-agent environments. Essential for ERP-SIM and CSIM — the stages where simulation is both the research method and the subject of study.',
        outputs: ['Emergence curves', 'Phase transition maps', 'Multi-agent behavior repertoires'],
        utiStages: [6, 7],
        uaiPillars: [4, 5],
      },
      {
        id: 'cross-domain-transfer',
        label: 'Cross-Domain Transfer Studies',
        maturity: 'Active Research',
        description: 'Measuring how well knowledge, structure, or causal models transfer from a source domain to a target domain. The primary evaluation method for ERP-X and UAIF substrate-independence claims.',
        outputs: ['Transfer accuracy metrics', 'Structural similarity scores', 'Causal transfer fidelity measures'],
        utiStages: [5],
        uaiPillars: [3, 7],
      },
      {
        id: 'longitudinal-continual',
        label: 'Longitudinal / Continual Learning Studies',
        maturity: 'Active Research',
        description: 'Experiments measuring system performance over extended time horizons — months or years — as new knowledge is added. Essential for validating memory architecture and catastrophic forgetting prevention.',
        outputs: ['Forgetting curves', 'Knowledge accumulation trajectories', 'Plasticity-stability tradeoffs'],
        utiStages: [3, 7, 10],
        uaiPillars: [6],
      },
    ],
  },
]

export const STAGE_LABELS = {
  1: { number: '00', title: 'Pre-Foundational', accent: '#64748b' },
  2: { number: '01', title: 'Information-Centric', accent: '#3b82f6' },
  3: { number: '02', title: 'Epistemic Intelligence', accent: '#8b5cf6' },
  4: { number: '03', title: 'Structural Intelligence', accent: '#f59e0b' },
  5: { number: '04', title: 'ERP-X Cross-Domain', accent: '#ec4899' },
  6: { number: '05', title: 'ERP-SIM Simulation', accent: '#14b8a6' },
  7: { number: '06', title: 'CSIM Metrics', accent: '#10b981' },
  8: { number: '07', title: 'Multi-Scale Unification', accent: '#6366f1' },
  9: { number: '08', title: 'Universal Theory', accent: '#f43f5e' },
  10: { number: '09', title: 'Eternal Research Program', accent: '#d946ef' },
}

export const PILLAR_LABELS = {
  1: { number: '01', title: 'Intelligence Gap', icon: '⚠️', accent: '#f43f5e' },
  2: { number: '02', title: 'Perception', icon: '👁️', accent: '#0ea5e9' },
  3: { number: '03', title: 'Grounding', icon: '🔗', accent: '#8b5cf6' },
  4: { number: '04', title: 'Knowledge Graph', icon: '🕸️', accent: '#10b981' },
  5: { number: '05', title: 'Causal Reasoning', icon: '⚡', accent: '#f59e0b' },
  6: { number: '06', title: 'Memory', icon: '🧠', accent: '#3b82f6' },
  7: { number: '07', title: 'Complete Vision', icon: '🌌', accent: '#d946ef' },
}
